
= IiU -- Asciidoctor Reveal.JS
Installation in Ubuntu — khkoether[at]kahweb[dot]de

include::_bp_header.adoc[]

:asciidoctor-revealjs-home-url: https://github.com/asciidoctor/asciidoctor-reveal.js/
:revealjs-home-url:             https://github.com/hakimel/reveal.js
:revealjs-download-url:         https://github.com/hakimel/reveal.js/releases/tag/3.8.0
:asciidoctor-github-url:        https://github.com/asciidoctor/asciidoctor
:asciidoctor-license-url:       https://github.com/asciidoctor/asciidoctor/blob/master/LICENSE.adoc

Version {version} {middot} {datum}


== Abstract
{asciidoctor-revealjs-home-url}[Asciidoctor reveal.js] ist ein Konverter der ein
_AsciiDoc_-Dokument in eine HTML5-Präsentation umwandelt, um mit dem Framework
_reveal.js_ ausgeführt zu werden.

_Asciidoctor_ ist Open Source,
wird gehostet auf {asciidoctor-github-url}[GitHub]
und ist freigegeben unter der {asciidoctor-license-url}[MIT-Lizenz].

Der Artikel ist in _AsciiDoc_ geschrieben
und mit _Asciidoctor {asciidoctor-version}_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschließend
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder
auf einem anderem Weg durchgeführt werden können. +
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====

.Asciidoctor reveal.js: Links
****
====
* {asciidoctor-revealjs-home-url}[Asciidoctor reveal.js]
* {revealjs-home-url}[reveal.js]
* {revealjs-home-url}#syntax-examples[Asciidoctor reveal.js: Syntax Examples]
====
****


== Vorraussetzung
Die Installation wird für {ubuntu-url}[Ubuntu 18.04 LTS (Bionic Beaver)] beschrieben. +
Gleichwohl sind die einzelnen Schritte auch für
andere Debian-basierte GNU/Linux Distributionen übertragbar.

Die System-Installation von *Ruby* ist,
wie in &nbsp; {asciidoctor-url}[IiU -- Asciidoctor] &nbsp; beschrieben,
durchgeführt worden.

[options="nowrap"]
----
$ COLUMNS=96 dpkg --list | grep ruby2.5   <1>
ii  libruby2.5:amd64   2.5.1-1ubuntu1 amd64          Libraries necessary to run Ruby 2.5
ii  ruby2.5            2.5.1-1ubuntu1 amd64          Interpreter of object-oriented scripting
ii  ruby2.5-dev:amd64  2.5.1-1ubuntu1 amd64          Header files for compiling extension modu
ii  ruby2.5-doc        2.5.1-1ubuntu1 all            Documentation for Ruby 2.5
----
<1> COLUMNS=96 ist eine Formatangabe für die Ausgabe von #dpkg#


== Download
* {revealjs-download-url}[reveal.js v3.8.0] +
  `reveal.js-3.8.0.tar.gz`  (ca. 1.8M) +
  2019-04-01 (Release date)


== Installation
Mithilfe des Befehls _sudo_ wird die System-Installation von *Ruby* ergänzt.

.RubyGems
* *asciidoctor-revealjs* +
  Reveal.JS back-end for Asciidoctor and Asciidoctor.js. Write slides in AsciiDoc!

----
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

$ sudo gem install asciidoctor-revealjs   <1>
[sudo] Passwort für sid:
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: concurrent-ruby-1.1.5.gem (100%)
Successfully installed concurrent-ruby-1.1.5
Fetching: asciidoctor-revealjs-2.0.0.gem (100%)
Successfully installed asciidoctor-revealjs-2.0.0
3 gems installed
----
<1> *Asciidoctor* ist bereits zuvor installiert worden.

----
$ gem list --local

*** LOCAL GEMS ***

asciidoctor (2.0.10)
asciidoctor-revealjs (2.0.0)   <1>
...
coderay (1.1.2)
concurrent-ruby (1.1.5)        <1>
...
thread_safe (0.3.6)            <1>
----
<1> 3 gems installed

[TIP]
====
Bei einer mit {chruby-url}[chruby] verwalteten *Ruby*-Version ist _sudo_ nicht notwendig.
----
$ gem install asciidoctor-revealjs
...
3 gems installed
----
====

[options="nowrap"]
----
$ asciidoctor-revealjs -V
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu])
                                   (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
----


== Asciidoctor reveal.js: Erste Schritte &hellip;
Eine Präsentation erstellen Sie mit _asciidoctor-revealjs_ auf dem folgendenden Weg:

.Framework: `reveal.js`
----
$ mkdir MyPresentation
$ cd MyPresentation

$ tar xvzf reveal.js-3.8.0.tar.gz
$ mv reveal.js-3.8.0 reveal.js
----

.Datei: `presentation.adoc`
----
= Title Slide


== Slide One
* Foo
* Bar
* World


== Slide Two
Hello World - Good Bye Cruel World

[NOTE.speaker]
--
Actually things aren't that bad
--


[background-color="yellow"]
== Slide Three
Here come's the sun...
----



.#asciidoctor-revealjs ...#
----
$ asciidoctor-revealjs presentation.adoc
----

.Browser: `presentation.html`
----
$ firefox presentation.html
----


== Asciidoctor reveal.js: Projektstruktur
----
$ tree -L 2 .
.
├── presentation.adoc   <1>
├── presentation.html
└── reveal.js
    ├── bower.json
    ├── CONTRIBUTING.md
    ├── css
    ├── demo.html
    ├── gruntfile.js
    ├── index.html
    ├── js
    ├── lib
    ├── LICENSE
    ├── package.json
    ├── package-lock.json
    ├── plugin
    ├── README.md
    └── test

6 directories, 11 files
----
<1> Eigene Präsentation


== Asciidoctor reveal.js: Variablen
Sie können die Ausgabe durch setzen von _reveal.js Variablen_ ändern!

.Datei: `presentation.adoc`
[source,asciidoc]
----
= Title Slide
Sid ~ Großstadt ~ 02.11.2019
:revealjs_theme: sky
:revealjs_slideNumber: true
:source-highlighter: coderay

[...]
----

.#asciidoctor-revealjs ...#
----
$ asciidoctor-revealjs presentation.adoc
----

.Browser: `presentation.html`
----
$ firefox presentation.html
----




include::_bp_footer.adoc[]
