IiU -- Git 1.9.0
================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by-sa/3.0/de/
:ubuntu-url: http://www.ubuntu.com/
:asciidoctor-url: http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:git-url: http://git-scm.com/
:git-download-url: http://code.google.com/p/git-core/downloads/list

:git-version: 1.9.0


Version 2.2.0, März 2014


Abstract
--------
Der Artikel ist eine Schritt-für-Schritt Anleitung zur Installation 
des Programms {git-url}[Git] aus dem QuellCode.
 
{git-url}[Git] ist ein freies verteiltes Versionskontrollsystem 
(DVCS - Distributed Version Control System).

Der Artikel ist in {asciidoctordocs-url}[AsciiDoc] geschrieben 
und mit _Asciidoctor 1.5.0.preview3_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzung
--------------
Die Installation wird für {ubuntu-url}[Ubuntu 12.04 LTS (Precise Pangolin)] 
beschrieben. +
Gleichwohl sind die einzelnen Schritte auch für 
andere Debian-basierte GNU/Linux Distributionen übertragbar.

[TIP]
====
Ubuntu 12.04 LTS (Precise Pangolin) enthält das Paket _git-core_1.7.9.5-1_all_.
====


Download
--------
* {git-download-url}[Git] +    
  +git-{git-version}.tar.gz+  (ca. 4.7M) +
  +git-htmldocs-{git-version}.tar.gz+  (ca. 2.2M) +
  +git-manpages-{git-version}.tar.gz+  (ca. 559K) +
  2014-02-14 (Release date)
  
[NOTE] 
====
Das Kompilieren des Versionskontrollsystem wird beispielhaft vom Benutzer 'sid' 
durchgeführt. +
Die eigentliche Installation von Git wird vom  
Benutzer 'root' für das System durchgeführt.
----
$ ls -l
-rw-rw-r--  1 sid  sid    4839724 Mär  2 16:16 git-1.9.0.tar.gz
-rw-rw-r--  1 sid  sid    2240600 Mär  2 16:16 git-htmldocs-1.9.0.tar.gz
-rw-rw-r--  1 sid  sid     571616 Mär  2 16:16 git-manpages-1.9.0.tar.gz
----
====

[NOTE] 
====
Vor der eigentlichen Installation müssen die fehlenden 
Programm-Pakete installiert sind.
----
$ sudo apt-get install ... 
                       build-essential libc6 libcurl3-gnutls libexpat1 libexpat1-dev 
                       autoconf zlib1g perl-modules liberror-perl libdigest-sha-perl 
                       libcurl4-openssl-dev libssl-dev tcl8.4  tcl8.4-dev xmlto
----
====


Installation
------------
[IMPORTANT]
====
Ohne die Angabe eines Verzeichnisses wird +/usr/local/...+ automatisch verwendet. +
Eine bereits vorhandene Git-Installation wird überschrieben. 
 
Beispiel für die Änderung des Installations-Verzeichnisses: +
+./configure --prefix=/opt/wo_auch_immer+
====

*Step 1:* Auspacken des Source-Code
----
$ tar xvzf git-1.9.0.tar.gz
$ cd git-1.9.0
----

*Step 2:* Konfiguration erstellen und kompilieren
----
$ make configure | tee ../log.git_make-configure
GIT_VERSION = 1.9.0
    GEN configure

$ ./configure | tee ../log.git_configure
configure: Setting lib to 'lib' (the default)
configure: Will try -pthread then -lpthread to enable POSIX Threads.
configure: CHECKS for site configuration
[...]
checking for asciidoc... asciidoc
checking for asciidoc version... asciidoc 8.6.9
[...]
configure: creating ./config.status
config.status: creating config.mak.autogen
config.status: executing config.mak.autogen commands
----

----
$ make | tee ../log.git_make
    * new build flags
    CC credential-store.o
[...]
    GEN bin-wrappers/test-wildmatch
    GEN git-remote-testgit
----

*Step 3:* Installation (als Benutzer 'root')
----
$ sudo make install | tee ../log.git_make-install
    GEN perl/PM.stamp
    SUBDIR perl
[...]
	./check_bindir "z$bindir" "z$execdir" "$bindir/git-add"
----

.Documentation: web-pages
----
$ cd /usr/local/share/doc
$ sudo mkdir git-doc

$ cd git-doc
$ sudo tar xvzf git-htmldocs-1.9.0.tar.gz
[...]
./git-unpack-file.html

$ cd ..
$ sudo chown -R root.root git-doc   <1>
$ sudo chmod -R a+rx git-doc

$ ls -l 
drwxr-xr-x 9 root root  4096 Dez  8 15:28 asciidoc
drwxr-xr-x 5 root root 20480 Feb 14 22:58 git-doc
----
<1> Unbedingt die Rechte an den Dateien und den Ordnern anpassen!

.Documentation: man-pages
----
$ cd /usr/local/share/man  
$ sudo tar xvzf git-manpages-1.9.0.tar.gz 
[...]
./man8/gitnamespaces.7

$ cd ..
$ sudo chown -R root.root man   <1>
$ sudo chmod -R a+rX man

$ ls -l
drwxr-xr-x 2 root root 4096 Feb 14 22:59 man1
drwxr-xr-x 2 root root 4096 Mär  2 16:27 man3
drwxr-xr-x 2 root root 4096 Feb 14 22:59 man5
drwxr-xr-x 2 root root 4096 Feb 14 22:59 man7
----
<1> Unbedingt die Rechte an den Dateien und den Ordnern anpassen!

*Step 4:* Installation verifizieren
----
$ cd /usr/local/bin
$ ls -l git*
-rwxr-xr-x 111 root root 7309559 Mär  2 16:27 git
-rwxr-xr-x   2 root root  162423 Mär  2 16:27 git-cvsserver
-rwxr-xr-x   1 root root  344042 Mär  2 16:27 gitk
-rwxr-xr-x 111 root root 7309559 Mär  2 16:27 git-receive-pack
-rwxr-xr-x   2 root root 3598463 Mär  2 16:27 git-shell
-rwxr-xr-x 111 root root 7309559 Mär  2 16:27 git-upload-archive
-rwxr-xr-x   2 root root 3669941 Mär  2 16:27 git-upload-pack
----

----
$ man git 
GIT(1)                            Git Manual                            GIT(1)

NAME
       git - the stupid content tracker

SYNOPSIS
       git [--version] [--help] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

DESCRIPTION
       Git is a fast, scalable, distributed revision control system with an
       unusually rich command set that provides both high-level operations and
       full access to internals.

       See gittutorial(7) to get started, then see Everyday Git[1] for a
       useful minimum set of commands, and "man git-commandname" for
       documentation of each command. CVS users may also want to read gitcvs-
       migration(7). See the Git User’s Manual[2] for a more in-depth
       introduction.

       The <command> is either a name of a Git command (see below) or an alias
       as defined in the configuration file (see git-config(1)).

       Formatted and hyperlinked version of the latest git documentation can
       be viewed at http://www.kernel.org/pub/software/scm/git/docs/.

[...]

AUTHORS
       Git was started by Linus Torvalds, and is currently maintained by Junio
       C Hamano. Numerous contributions have come from the git mailing list
       <git@vger.kernel.org[6]>. For a more complete list of contributors, see
       http://git-scm.com/about. If you have a clone of git.git itself, the
       output of git-shortlog(1) and git-blame(1) can show you the authors for
       specific parts of the project.

REPORTING BUGS
       Report bugs to the Git mailing list <git@vger.kernel.org[6]> where the
       development and maintenance is primarily done. You do not have to be
       subscribed to the list to send a message there.

SEE ALSO
       gittutorial(7), gittutorial-2(7), Everyday Git[1], gitcvs-migration(7),
       gitglossary(7), gitcore-tutorial(7), gitcli(7), The Git User’s
       Manual[2], gitworkflows(7)

GIT
       Part of the git(1) suite

NOTES
        1. Everyday Git
           file:///usr/local/share/doc/git-doc/everyday.html

        2. Git User’s Manual
           file:///usr/local/share/doc/git-doc/user-manual.html

        3. git concepts chapter of the user-manual
           file:///usr/local/share/doc/git-doc/user-manual.html#git-concepts

        4. howto
           file:///usr/local/share/doc/git-doc/howto-index.html

        5. GIT API documentation
           file:///usr/local/share/doc/git-doc/technical/api-index.html

        6. git@vger.kernel.org
           mailto:git@vger.kernel.org

Git 1.9.0                         02/14/2014                            GIT(1)
----
 
----
$ man gitk 
GITK(1)                           Git Manual                           GITK(1)

NAME
       gitk - The git repository browser

SYNOPSIS
       gitk [<option>...] [<revs>] [--] [<path>...]

DESCRIPTION
       Displays changes in a repository or a selected set of commits. This
       includes visualizing the commit graph, showing information related to
       each commit, and the files in the trees of each revision.

       Historically, gitk was the first repository browser. It’s written in
       tcl/tk and started off in a separate repository but was later merged
       into the main git repository.

[...]

EXAMPLES
       gitk v2.6.12.. include/scsi drivers/scsi
           Show the changes since version v2.6.12 that changed any file in the
           include/scsi or drivers/scsi subdirectories

       gitk --since="2 weeks ago" -- gitk
           Show the changes during the last two weeks to the file gitk. The
           "--" is necessary to avoid confusion with the branch named gitk

       gitk --max-count=100 --all -- Makefile
           Show at most 100 changes made to the file Makefile. Instead of only
           looking for changes in the current branch look in all branches.

FILES
       Gitk creates the .gitk file in your $HOME directory to store
       preferences such as display options, font, and colors.

SEE ALSO
       qgit(1)
           A repository browser written in C++ using Qt.

       gitview(1)
           A repository browser written in Python using Gtk. It’s based on
           bzrk(1) and distributed in the contrib area of the git repository.

       tig(1)
           A minimal repository browser and git tool output highlighter
           written in C using Ncurses.

GIT
       Part of the git(1) suite

Git 1.9.0                         02/14/2014                           GITK(1)
----

----
$ find /usr/local -type d -cmin -10
/usr/local/share/git-core/templates
/usr/local/share/git-core/templates/hooks
/usr/local/share/git-core/templates/branches
/usr/local/share/git-core/templates/info
/usr/local/share/git-gui/lib
/usr/local/share/git-gui/lib/msgs
/usr/local/share/doc
/usr/local/share/doc/git-doc
/usr/local/share/doc/git-doc/howto
/usr/local/share/doc/git-doc/technical
/usr/local/share/doc/git-doc/RelNotes
/usr/local/share/man
/usr/local/share/man/man7
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man1
/usr/local/share/perl/5.14.2/Git
/usr/local/share/perl/5.14.2/Git/SVN
/usr/local/share/gitweb
/usr/local/share/gitweb/static
/usr/local/share/gitk/lib/msgs
/usr/local/share/locale
/usr/local/share/locale/is
/usr/local/share/locale/is/LC_MESSAGES
/usr/local/share/locale/bg
/usr/local/share/locale/bg/LC_MESSAGES
/usr/local/share/locale/fr
/usr/local/share/locale/fr/LC_MESSAGES
/usr/local/share/locale/it
/usr/local/share/locale/it/LC_MESSAGES
/usr/local/share/locale/sv
/usr/local/share/locale/sv/LC_MESSAGES
/usr/local/share/locale/pt_PT
/usr/local/share/locale/pt_PT/LC_MESSAGES
/usr/local/share/locale/vi
/usr/local/share/locale/vi/LC_MESSAGES
/usr/local/share/locale/de
/usr/local/share/locale/de/LC_MESSAGES
/usr/local/share/locale/zh_CN
/usr/local/share/locale/zh_CN/LC_MESSAGES
/usr/local/bin
/usr/local/libexec/git-core
/usr/local/libexec/git-core/mergetools
----

*Step 5:* Dokumentation (local)

.git(1) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/index.html

.gittutorial(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gittutorial.html

.gittutorial-2(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gittutorial-2.html

.Everyday GIT With 20 Commands Or So
Browser> file:///usr/local/share/doc/git-doc/everyday.html

.gitglossary(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitglossary.html

.gitcore-tutorial(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitcore-tutorial.html

.gitcli(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitcli.html

.Git User’s Manual (for version 1.5.3 or newer)
Browser> file:///usr/local/share/doc/git-doc/user-manual.html

.gitworkflows(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitworkflows.html

.git-config(1) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/git-config.html


Anhang
------
Script zum Installieren von Git {git-version} (ohne weitere Erläuterung).
Die Dokumentation wird mit diesem Script _nicht_ installiert.

.Datei: +git-install.sh+
----
#!/bin/bash
#
ME=make_git
NAME=git-1.9.0

ls -l git*.tar.gz
echo 

echo "Git-Installation fortsetzen (j/n)"
read dummy
case $dummy in
  j|J|y|Y) echo "Installation wird fortgesetzt."
           ;;
  *) echo "Installation wird abgebrochen."
     exit 1
     ;;
esac

echo 
echo "Source auspacken ..."
tar xvzf ${NAME}.tar.gz
cd ${NAME}

echo 
echo "Source übersetzen ..."
make configure | tee ../log.git_make-configure
./configure | tee ../log.git_configure
make | tee ../log.git_make

echo
echo "Git installieren"
sudo make install | tee ../log.git_make-install

echo "Dokumentation fehlt!" 

echo
cd /usr/local/bin
ls -l git*

echo 
echo "$ME: Ende."
----
