
= IiU -- Git 2.20.0
Installation in Ubuntu — khkoether[at]kahweb[dot]de

include::_bp_header.adoc[]

:git-home-url:       https://git-scm.com/
:git-download-url:   https://www.kernel.org/pub/software/scm/git/

Version {version} {middot} {datum}


== Abstract
{git-home-url}[Git] ist ein freies verteiltes Versionskontrollsystem
(DVCS - Distributed Version Control System).

Der Artikel ist eine Schritt-für-Schritt Anleitung zur Installation
des Programms {git-home-url}[Git] aus dem QuellCode.

_Git_ ist Open Source und ist freigegeben
unter der {gpl-url}[GPL v2-Lizenz].


Der Artikel ist in _AsciiDoc_ geschrieben
und mit _Asciidoctor {asciidoctor-version}_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder
auf einem anderem Weg durchgeführt werden können. +
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


== Vorraussetzung
Die Installation wird für {ubuntu-url}[Ubuntu 18.04 LTS (Bionic Beaver)] beschrieben. +
Gleichwohl sind die einzelnen Schritte auch für
andere Debian-basierte GNU/Linux Distributionen übertragbar.

[TIP]
====
Ubuntu 18.04 LTS (Bionic Beaver) enthält das Paket::
  _git_2.17.1-1ubuntu0.4_amd64.deb_

----
$ git --version
git version 2.17.1
----
====


== Download
* {git-download-url}[Git] +
  `git-2.20.0.tar.gz`  &nbsp; -- &nbsp; ca. 8M +
  `git-htmldocs-2.20.0.tar.gz` &nbsp; -- &nbsp; ca. 3M +
  `git-manpages-2.20.0.tar.gz` &nbsp; -- &nbsp; ca. 697K +
  2018-12-09 (Release date) --
  https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.20.0.txt[Git 2.20 Release Notes]

[NOTE]
====
Das Kompilieren des Versionskontrollsystem wird beispielhaft
vom Benutzer 'sid' durchgeführt. +
Die eigentliche Installation von Git wird vom
Benutzer 'root' für das System durchgeführt.
----
$ ls -lh
-rw-rw-r-- 1 sid sid 7,6M Dez 10 20:30 git-2.20.0.tar.gz
-rw-rw-r-- 1 sid sid 2,9M Dez 10 20:31 git-htmldocs-2.20.0.tar.gz
-rw-rw-r-- 1 sid sid 698K Dez 10 20:31 git-manpages-2.20.0.tar.gz
----
====


== Installation
[CAUTION]
====
Zur Installation von *Git* müssen weitere Pakete installiert sein.

[options="nowrap"]
----
$ sudo apt update
$ sudo apt upgrade
$ sudo apt install make libssl-dev libghc-zlib-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip   <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
make ist schon die neueste Version (4.1-9.1ubuntu1).
unzip ist schon die neueste Version (6.0-21ubuntu1).
gettext ist schon die neueste Version (0.19.8.1-6ubuntu0.1).
Die folgenden zusätzlichen Pakete werden installiert:
  ghc libbsd-dev libffi-dev libncurses5-dev libssl-doc libtinfo-dev
Vorgeschlagene Pakete:
  ghc-prof ghc-doc haskell-doc llvm-3.7 libcurl4-doc libgnutls28-dev
  libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev pkg-config
  libghc-zlib-doc libghc-zlib-prof ncurses-doc
Die folgenden NEUEN Pakete werden installiert:
  ghc libbsd-dev libcurl4-gnutls-dev libexpat1-dev libffi-dev libghc-zlib-dev
  libncurses5-dev libssl-dev libssl-doc libtinfo-dev
0 aktualisiert, 10 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 49,1 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 584 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n]
----
<1> Der *GCC* ist standardmäßig bereits vorhanden.
====

[IMPORTANT]
====
Ohne die Angabe eines Verzeichnisses wird `/usr/local/...` automatisch verwendet. +
Eine bereits vorhandene Git-Installation wird überschrieben.

Beispiel für die Änderung des Installations-Verzeichnisses: +
#./configure --prefix=/opt/wo_auch_immer#
====

*Step 1:* Auspacken des Source-Code
----
$ tar xvzf git-2.20.0.tar.gz
$ cd git-2.20.0
----

*Step 2:* Konfiguration erstellen und kompilieren
----
$ make configure | tee ../log.git_make-configure
GIT_VERSION = 2.20.0
    GEN configure

$ ./configure | tee ../log.git_configure
configure: Setting lib to 'lib' (the default)
configure: Will try -pthread then -lpthread to enable POSIX Threads.
configure: CHECKS for site configuration
checking for gcc... gcc
[...]
configure: creating ./config.status
config.status: creating config.mak.autogen
config.status: executing config.mak.autogen commands
----

----
$ make all | tee ../log.git_make-all
    * new build flags
    CC fuzz-pack-headers.o
    ...
    GEN bin-wrappers/test-tool
    GEN git-remote-testgit
----

*Step 3:* Installation (als Benutzer 'root')
----
$ sudo make install | tee ../log.git_make-install   <1>
    SUBDIR git-gui
    SUBDIR gitk-git
    SUBDIR templates
install -d -m 755 '/usr/local/bin'
install -d -m 755 '/usr/local/libexec/git-core'
...
./check_bindir "z$bindir" "z$execdir" "$bindir/git-add"
----
<1> Die Installation wird bei mir im Verzeichnis `/usr/local/bin` ausgeführt.

----
$ ls -l /usr/local/bin | grep git
-rwxr-xr-x 127 root root 15715888 Dez 10 20:40 git
-rwxr-xr-x   2 root root   162737 Dez 10 20:40 git-cvsserver
-rwxr-xr-x   1 root root   351673 Dez 10 20:40 gitk
-rwxr-xr-x 127 root root 15715888 Dez 10 20:40 git-receive-pack
-rwxr-xr-x   2 root root  8985560 Dez 10 20:40 git-shell
-rwxr-xr-x 127 root root 15715888 Dez 10 20:40 git-upload-archive
-rwxr-xr-x 127 root root 15715888 Dez 10 20:40 git-upload-pack
----

.Documentation: web-pages
----
$ cd /usr/local/share/doc
$ sudo mkdir git-doc

$ cd git-doc
$ sudo tar xvzf git-htmldocs-2.20.0.tar.gz
...
./git-credential-cache.html
./user-manual.html
./git-pull.html

$ cd ..
$ sudo chown -R root.root git-doc   <1>
$ sudo chmod -R a+r git-doc
$ sudo chmod a+rx git-doc

$ ls -l
drwxr-xr-x 2 root root  4096 Nov  5 21:34 chruby-0.3.9
drwxr-sr-x 5 root root 20480 Dez  9 05:51 git-doc        <2>
----
<1> Unbedingt die Rechte an den Dateien und den Ordnern anpassen!
<2> Release Date: 2018-12-09

.Documentation: man-pages
----
$ cd /usr/local/share/man
$ sudo tar xvzf git-manpages-2.20.0.tar.gz
...
./man1/git-credential-store.1
./man1/git-imap-send.1

$ cd ..
$ sudo chown -R root.root man   <1>
$ sudo chmod -R a+r man
$ sudo chmod 755 man man/man1 man/man5 man/man7


$ ls -l man
drwxr-sr-x 2 root root 4096 Dez  9 15:59 man1  <2>
drwxr-sr-x 2 root root 4096 Dez  9 15:59 man5   <2>
drwxr-sr-x 2 root root 4096 Dez  9 15:59 man7   <2>
----
<1> Unbedingt die Rechte an den Dateien und den Ordnern anpassen!
<2> Release Date: 2018-12-09


== Installation verifizieren


=== git --version
----
$ git --version
git version 2.20.0
----


=== man git
----
$ man git
GIT(1)                            Git Manual                            GIT(1)

NAME
       git - the stupid content tracker

SYNOPSIS
       git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>]
          <command> [<args>]

DESCRIPTION
       Git is a fast, scalable, distributed revision control system with an
       unusually rich command set that provides both high-level operations and
       full access to internals.

       See gittutorial(7) to get started, then see giteveryday(7) for a useful
       minimum set of commands. The Git User’s Manual[1] has a more in-depth
       introduction.

       After you mastered the basic concepts, you can come back to this page
       to learn what commands Git offers. You can learn more about individual
       Git commands with "git help command". gitcli(7) manual page gives you
       an overview of the command-line command syntax.

       A formatted and hyperlinked copy of the latest Git documentation can be
       viewed at https://git.github.io/htmldocs/git.html.

[...]

AUTHORS
       Git was started by Linus Torvalds, and is currently maintained by Junio
       C Hamano. Numerous contributions have come from the Git mailing list
       <git@vger.kernel.org[5]>.
       http://www.openhub.net/p/git/contributors/summary gives you a more
       complete list of contributors.

       If you have a clone of git.git itself, the output of git-shortlog(1)
       and git-blame(1) can show you the authors for specific parts of the
       project.

REPORTING BUGS
       Report bugs to the Git mailing list <git@vger.kernel.org[5]> where the
       development and maintenance is primarily done. You do not have to be
       subscribed to the list to send a message there.

SEE ALSO
       gittutorial(7), gittutorial-2(7), giteveryday(7), gitcvs-migration(7),
       gitglossary(7), gitcore-tutorial(7), gitcli(7), The Git User’s
       Manual[1], gitworkflows(7)

GIT
       Part of the git(1) suite

NOTES
        1. Git User’s Manual
           git-htmldocs/user-manual.html

        2. Git concepts chapter of the user-manual
           git-htmldocs/user-manual.html#git-concepts

        3. howto
           git-htmldocs/howto-index.html

        4. Git API documentation
           git-htmldocs/technical/api-index.html

        5. git@vger.kernel.org
           mailto:git@vger.kernel.org

        6. git-security@googlegroups.com
           mailto:git-security@googlegroups.com


Git 2.20.0                        12/09/2018                            GIT(1)
----


=== man gitk
----
$ man gitk
GITK(1)                           Git Manual                           GITK(1)

NAME
       gitk - The git repository browser

SYNOPSIS
       gitk [<options>] [<revision range>] [--] [<path>...]

DESCRIPTION
       Displays changes in a repository or a selected set of commits. This
       includes visualizing the commit graph, showing information related to
       each commit, and the files in the trees of each revision.

[...]

HISTORY
       Gitk was the first graphical repository browser. It’s written in
       tcl/tk.

       gitk is actually maintained as an independent project, but stable
       versions are distributed as part of the Git suite for the convenience
       of end users.

       gitk-git/ comes from Paul Mackerras’s gitk project:

           git://ozlabs.org/~paulus/gitk

SEE ALSO
       qgit(1)
           A repository browser written in C++ using Qt.

       tig(1)
           A minimal repository browser and Git tool output highlighter
           written in C using Ncurses.

GIT
       Part of the git(1) suite

Git 2.20.0                        12/09/2018                           GITK(1)
----


=== /usr/local
----
$ sudo find /usr/local -type d -cmin -30
/usr/local/bin
/usr/local/share/gitweb
/usr/local/share/gitweb/static
/usr/local/share/man
/usr/local/share/man/man5
/usr/local/share/man/man1
/usr/local/share/man/man7
/usr/local/share/git-core/templates
/usr/local/share/git-core/templates/hooks
/usr/local/share/git-core/templates/info
/usr/local/share/git-core/templates/branches
/usr/local/share/locale
/usr/local/share/locale/pt_PT
/usr/local/share/locale/pt_PT/LC_MESSAGES
/usr/local/share/locale/ru
/usr/local/share/locale/ru/LC_MESSAGES
/usr/local/share/locale/sv
/usr/local/share/locale/sv/LC_MESSAGES
/usr/local/share/locale/bg
/usr/local/share/locale/bg/LC_MESSAGES
/usr/local/share/locale/is
/usr/local/share/locale/is/LC_MESSAGES
/usr/local/share/locale/it
/usr/local/share/locale/it/LC_MESSAGES
/usr/local/share/locale/fr
/usr/local/share/locale/fr/LC_MESSAGES
/usr/local/share/locale/zh_CN
/usr/local/share/locale/zh_CN/LC_MESSAGES
/usr/local/share/locale/de
/usr/local/share/locale/de/LC_MESSAGES
/usr/local/share/locale/ko
/usr/local/share/locale/ko/LC_MESSAGES
/usr/local/share/locale/es
/usr/local/share/locale/es/LC_MESSAGES
/usr/local/share/locale/vi
/usr/local/share/locale/vi/LC_MESSAGES
/usr/local/share/locale/ca
/usr/local/share/locale/ca/LC_MESSAGES
/usr/local/share/git-gui/lib
/usr/local/share/git-gui/lib/msgs
/usr/local/share/perl5
/usr/local/share/perl5/FromCPAN
/usr/local/share/perl5/FromCPAN/Mail
/usr/local/share/perl5/Git
/usr/local/share/perl5/Git/SVN
/usr/local/share/perl5/Git/SVN/Memoize
/usr/local/share/perl5/Git/LoadCPAN
/usr/local/share/perl5/Git/LoadCPAN/Mail
/usr/local/share/doc
/usr/local/share/doc/git-doc
/usr/local/share/doc/git-doc/howto
/usr/local/share/doc/git-doc/technical
/usr/local/share/doc/git-doc/RelNotes
/usr/local/share/gitk/lib/msgs
/usr/local/libexec/git-core
/usr/local/libexec/git-core/mergetools
----


== Dokumentation (local)
.git(1) Manual Page
Browser> file:///usr/local/share/doc/git-doc/index.html

.gittutorial(7) Manual Page
Browser> file:///usr/local/share/doc/git-doc/gittutorial.html

.gittutorial-2(7) Manual Page
Browser> file:///usr/local/share/doc/git-doc/gittutorial-2.html

.Everyday GIT With 20 Commands Or So
Browser> file:///usr/local/share/doc/git-doc/everyday.html

.gitglossary(7) Manual Page
Browser> file:///usr/local/share/doc/git-doc/gitglossary.html

.gitcore-tutorial(7) Manual Page
Browser> file:///usr/local/share/doc/git-doc/gitcore-tutorial.html

.gitcli(7) Manual Page
Browser> file:///usr/local/share/doc/git-doc/gitcli.html

.Git User’s Manual
Browser> file:///usr/local/share/doc/git-doc/user-manual.html

.gitworkflows(7) Manual Page
Browser> file:///usr/local/share/doc/git-doc/gitworkflows.html

.git-config(1) Manual Page
Browser> file:///usr/local/share/doc/git-doc/git-config.html


== Anhang
Script zum Installieren von {git-url}[Git] 2.20.0 (ohne weitere Erläuterung). +
Die Dokumentation zu {git-url}[Git] wird mit diesem Script _nicht_ installiert.

.Datei: `git-install.sh`
----
#!/bin/bash
#
ME=make_git
NAME=git-2.20.0

ls -l git*.tar.gz
echo

echo "Git-Installation fortsetzen (j/n)"
read dummy
case $dummy in
  j|J|y|Y) echo "Installation wird fortgesetzt."
           ;;
  *) echo "Installation wird abgebrochen."
     exit 1
     ;;
esac

echo
echo "Source auspacken ..."
tar xvzf ${NAME}.tar.gz
cd ${NAME}

echo
echo "Source übersetzen ..."
make configure | tee ../log.git_make-configure
./configure | tee ../log.git_configure
make all | tee ../log.git_make-all

echo
echo "Git installieren"
sudo make install | tee ../log.git_make-install

echo "Dokumentation fehlt!"

echo
cd /usr/local/bin
ls -l git*

echo
echo "$ME: Ende."
----




include::_bp_footer.adoc[]
