IiU -- Git 2.7.0
================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: khk
:creativecommons-url: http://creativecommons.org/licenses/by/4.0/deed.de
:mit-url:             http://opensource.org/licenses/mit-license.php  
:ubuntu-url:          http://www.ubuntu.com/
:asciidoctor-url:     http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/

:git-url:             http://git-scm.com/
:git-download-url:    https://www.kernel.org/pub/software/scm/git/
:git-version: 2.7.0

Version 4.0.0, Januar 2016


Abstract
--------
Der Artikel ist eine Schritt-für-Schritt Anleitung zur Installation 
des Programms {git-url}[Git] aus dem QuellCode.
 
{git-url}[Git] ist ein freies verteiltes Versionskontrollsystem 
(DVCS - Distributed Version Control System).

Der Artikel ist in {asciidoctordocs-url}[Asciidoctor] geschrieben 
und mit _Asciidoctor {asciidoctor-version}_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzung
--------------
Die Installation wird für {ubuntu-url}[Ubuntu 14.04 LTS (Trusty Tahr)] 
beschrieben. +
Gleichwohl sind die einzelnen Schritte auch für 
andere Debian-basierte GNU/Linux Distributionen übertragbar.

[TIP]
====
Ubuntu 14.04 LTS (Trusty Tahr) enthält das Paket _git-core_1.9.1-1_all_.
====


Download
--------
* {git-download-url}[Git] +    
  `git-2.7.0.tar.gz`  (ca. 5.4M) +
  `git-htmldocs-2.7.0.tar.gz`  (ca. 2.4M) +
  `git-manpages-2.7.0.tar.gz`  (ca. 598K) +
  2016-01-04 (Release date)
  
[NOTE] 
====
Das Kompilieren des Versionskontrollsystem wird beispielhaft vom Benutzer 'sid' 
durchgeführt. +
Die eigentliche Installation von Git wird vom  
Benutzer 'root' für das System durchgeführt.
----
$ ls -lh
-rw-rw-r-- 1 sid sid 5,4M Jan  8 18:05 git-2.7.0.tar.gz
-rw-rw-r-- 1 sid sid 2,4M Jan  8 18:04 git-htmldocs-2.7.0.tar.gz
-rw-rw-r-- 1 sid sid 599K Jan  8 18:05 git-manpages-2.7.0.tar.gz
----
====

[NOTE] 
====
Vor der eigentlichen Installation müssen die fehlenden 
Programm-Pakete installiert sind.
----
$ sudo apt-get install ... 
               build-essential libc6 libcurl3-gnutls libexpat1 libexpat1-dev 
               autoconf zlib1g perl-modules liberror-perl libdigest-sha-perl 
               libcurl4-openssl-dev libssl-dev tcl8.4  tcl8.4-dev xmlto
----
====


Installation
------------
[IMPORTANT]
====
Ohne die Angabe eines Verzeichnisses wird `/usr/local/...` automatisch verwendet. +
Eine bereits vorhandene Git-Installation wird überschrieben. 
 
Beispiel für die Änderung des Installations-Verzeichnisses: +
#./configure --prefix=/opt/wo_auch_immer#
====

*Step 1:* Auspacken des Source-Code
----
$ tar xvzf git-2.7.0.tar.gz
$ cd git-2.7.0
----

*Step 2:* Konfiguration erstellen und kompilieren
----
$ make configure | tee ../log.git_make-configure
GIT_VERSION = 2.7.0
    GEN configure

$ ./configure | tee ../log.git_configure
configure: Setting lib to 'lib' (the default)
configure: Will try -pthread then -lpthread to enable POSIX Threads.
configure: CHECKS for site configuration
checking for gcc... gcc
[...]
configure: creating ./config.status
config.status: creating config.mak.autogen
config.status: executing config.mak.autogen commands
----

----
$ make | tee ../log.git_make
    * new build flags
    CC credential-store.o
    ...
    GEN bin-wrappers/test-wildmatch
    GEN git-remote-testgit
----

*Step 3:* Installation (als Benutzer 'root')
----
$ sudo make install | tee ../log.git_make-install   <1>
    GEN perl/PM.stamp
    SUBDIR perl
    ...
    ./check_bindir "z$bindir" "z$execdir" "$bindir/git-add"
----
<1> Die Installation wird bei mir im Verzeichnis `/usr/local/bin` ausgeführt.

.Documentation: web-pages
----
$ cd /usr/local/share/doc
$ sudo mkdir git-doc

$ cd git-doc
$ sudo tar xvzf git-htmldocs-2.7.0.tar.gz
...
./git-unpack-file.html

$ cd ..
$ sudo chown -R root.root git-doc   <1>
$ sudo chmod -R a+rx git-doc

$ ls -l 
drwxr-xr-x 5 root root 20480 Jan  5 00:32 git-doc
----
<1> Unbedingt die Rechte an den Dateien und den Ordnern anpassen!

.Documentation: man-pages
----
$ cd /usr/local/share/man  
$ sudo tar xvzf git-manpages-2.7.0.tar.gz 
...
./man7/giteveryday.7

$ cd ..
$ sudo chown -R root.root man   <1>
$ sudo chmod -R a+rx man

$ ls -l man
drwxr-xr-x 2 root root 4096 Jan  5 00:33 man1
drwxrwxr-x 2 root root 4096 Jan  8 18:12 man3
drwxr-xr-x 2 root root 4096 Jan  5 00:33 man5
drwxr-xr-x 2 root root 4096 Jan  5 00:33 man7
----
<1> Unbedingt die Rechte an den Dateien und den Ordnern anpassen!

*Step 4:* Installation verifizieren
----
$ cd /usr/local/bin
$ ls -l git*
-rwxr-xr-x 117 root root 9834835 Jan  8 18:12 git
-rwxr-xr-x   2 root root  162423 Jan  8 18:12 git-cvsserver
-rwxr-xr-x   1 root root  348785 Jan  8 18:12 gitk
-rwxr-xr-x 117 root root 9834835 Jan  8 18:12 git-receive-pack
-rwxr-xr-x   2 root root 4737325 Jan  8 18:12 git-shell
-rwxr-xr-x 117 root root 9834835 Jan  8 18:12 git-upload-archive
-rwxr-xr-x   2 root root 5169432 Jan  8 18:12 git-upload-pack
----

----
$ git --version
git version 2.7.0
----

----
$ man git 
GIT(1)                            Git Manual                            GIT(1)

NAME
       git - the stupid content tracker

SYNOPSIS
       git [--version] [--help] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

DESCRIPTION
       Git is a fast, scalable, distributed revision control system with an
       unusually rich command set that provides both high-level operations and
       full access to internals.

       See gittutorial(7) to get started, then see giteveryday(7) for a useful
       minimum set of commands. The Git User’s Manual[1] has a more in-depth
       introduction.

       After you mastered the basic concepts, you can come back to this page
       to learn what commands Git offers. You can learn more about individual
       Git commands with "git help command". gitcli(7) manual page gives you
       an overview of the command-line command syntax.

       Formatted and hyperlinked version of the latest Git documentation can
       be viewed at http://git-htmldocs.googlecode.com/git/git.html.

...

AUTHORS
       Git was started by Linus Torvalds, and is currently maintained by Junio
       C Hamano. Numerous contributions have come from the Git mailing list
       <git@vger.kernel.org[5]>.
       http://www.openhub.net/p/git/contributors/summary gives you a more
       complete list of contributors.

       If you have a clone of git.git itself, the output of git-shortlog(1)
       and git-blame(1) can show you the authors for specific parts of the
       project.

REPORTING BUGS
       Report bugs to the Git mailing list <git@vger.kernel.org[5]> where the
       development and maintenance is primarily done. You do not have to be
       subscribed to the list to send a message there.

SEE ALSO
       gittutorial(7), gittutorial-2(7), giteveryday(7), gitcvs-migration(7),
       gitglossary(7), gitcore-tutorial(7), gitcli(7), The Git User’s
       Manual[1], gitworkflows(7)

GIT
       Part of the git(1) suite

NOTES
        1. Git User’s Manual
           git-htmldocs/user-manual.html

        2. Git concepts chapter of the user-manual
           git-htmldocs/user-manual.html#git-concepts

        3. howto
           git-htmldocs/howto-index.html

        4. Git API documentation
           git-htmldocs/technical/api-index.html

        5. git@vger.kernel.org
           mailto:git@vger.kernel.org

Git 2.7.0                         01/04/2016                            GIT(1)
----
 
----
$ man gitk 
GITK(1)                           Git Manual                           GITK(1)

NAME
       gitk - The git repository browser

SYNOPSIS
       gitk [<option>...] [<revs>] [--] [<path>...]

DESCRIPTION
       Displays changes in a repository or a selected set of commits. This
       includes visualizing the commit graph, showing information related to
       each commit, and the files in the trees of each revision.

[...]

HISTORY
       Gitk was the first graphical repository browser. It’s written in tcl/tk
       and started off in a separate repository but was later merged into the
       main Git repository.

SEE ALSO
       qgit(1)
           A repository browser written in C++ using Qt.

       gitview(1)
           A repository browser written in Python using Gtk. It’s based on
           bzrk(1) and distributed in the contrib area of the Git repository.

       tig(1)
           A minimal repository browser and Git tool output highlighter
           written in C using Ncurses.

GIT
       Part of the git(1) suite

Git 2.7.0                         01/04/2016                           GITK(1)
----

----
$ find /usr/local -type d -cmin -10
/usr/local/share/gitweb
/usr/local/share/gitweb/static
/usr/local/share/git-core/templates
/usr/local/share/git-core/templates/hooks
/usr/local/share/git-core/templates/info
/usr/local/share/git-core/templates/branches
/usr/local/share/locale
/usr/local/share/locale/ru
/usr/local/share/locale/ru/LC_MESSAGES
/usr/local/share/locale/ca
/usr/local/share/locale/ca/LC_MESSAGES
/usr/local/share/locale/it
/usr/local/share/locale/it/LC_MESSAGES
/usr/local/share/locale/vi
/usr/local/share/locale/vi/LC_MESSAGES
/usr/local/share/locale/de
/usr/local/share/locale/de/LC_MESSAGES
/usr/local/share/locale/pt_PT
/usr/local/share/locale/pt_PT/LC_MESSAGES
/usr/local/share/locale/sv
/usr/local/share/locale/sv/LC_MESSAGES
/usr/local/share/locale/fr
/usr/local/share/locale/fr/LC_MESSAGES
/usr/local/share/locale/is
/usr/local/share/locale/is/LC_MESSAGES
/usr/local/share/locale/bg
/usr/local/share/locale/bg/LC_MESSAGES
/usr/local/share/locale/zh_CN
/usr/local/share/locale/zh_CN/LC_MESSAGES
/usr/local/share/perl/5.18.2/Git
/usr/local/share/git-gui/lib
/usr/local/share/git-gui/lib/msgs
/usr/local/share/gitk/lib/msgs
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
/usr/local/share/man/man7
/usr/local/share/doc
/usr/local/share/doc/git-doc
/usr/local/share/doc/git-doc/RelNotes
/usr/local/share/doc/git-doc/howto
/usr/local/share/doc/git-doc/technical
/usr/local/libexec/git-core
/usr/local/libexec/git-core/mergetools
/usr/local/bin
----

*Step 5:* Dokumentation (local)

.git(1) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/index.html

.gittutorial(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gittutorial.html

.gittutorial-2(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gittutorial-2.html

.Everyday GIT With 20 Commands Or So
Browser> file:///usr/local/share/doc/git-doc/everyday.html

.gitglossary(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitglossary.html

.gitcore-tutorial(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitcore-tutorial.html

.gitcli(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitcli.html

.Git User’s Manual (for version 1.5.3 or newer)
Browser> file:///usr/local/share/doc/git-doc/user-manual.html

.gitworkflows(7) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/gitworkflows.html

.git-config(1) Manual Page 
Browser> file:///usr/local/share/doc/git-doc/git-config.html


Anhang
------
Script zum Installieren von {git-url}[Git] 2.7.0 (ohne weitere Erläuterung). +
Die Dokumentation zu {git-url}[Git] wird mit diesem Script _nicht_ installiert.

.Datei: `git-install.sh`
----
#!/bin/bash
#
ME=make_git
NAME=git-2.7.0

ls -l git*.tar.gz
echo 

echo "Git-Installation fortsetzen (j/n)"
read dummy
case $dummy in
  j|J|y|Y) echo "Installation wird fortgesetzt."
           ;;
  *) echo "Installation wird abgebrochen."
     exit 1
     ;;
esac

echo 
echo "Source auspacken ..."
tar xvzf ${NAME}.tar.gz
cd ${NAME}

echo 
echo "Source übersetzen ..."
make configure | tee ../log.git_make-configure
./configure | tee ../log.git_configure
make | tee ../log.git_make

echo
echo "Git installieren"
sudo make install | tee ../log.git_make-install

echo "Dokumentation fehlt!" 

echo
cd /usr/local/bin
ls -l git*

echo 
echo "$ME: Ende."
----




'''
 
+++
<a href="#top" title="zum Seitenanfang">
  <span>&#8679;</span> 
</a>
+++
[small]#&middot; Document generated with Asciidoctor {asciidoctor-version}.#


