
= IiU -- OpenJDK 8/11
Installation in Ubuntu — khkoether[at]kahweb[dot]de

include::_bp_header.adoc[]

:java-home-url:            http://www.oracle.com/technetwork/java/javase/downloads/index.html

Version 5.2.0 {middot} Dezember 2018


== Abstract
{java-home-url}[Java] ist eine objektorientierte Programmiersprache. +
*Java* ist plattformunabhängig und für verschiedene
_Script_-Sprachen (_JRuby_, _Jython_) gibt es eine Implementation in *Java*.

Zum entwickeln von Anwendungen in *Java* ist das *Java Development Kit*
(kurz: *JDK*) notwendig.

*OpenJDK* ist die offizielle _freie_ Implementierung der _Java Platform_.

*Java* ist eine eingetragene Marke der Firma _Oracle_.

Dieser Artikel ist eine Schritt-für-Schritt Anleitung zur Installation
eines _Java Development Kit (JDK)_ unter _GNU/Linux_.

Die Artikel sind in _AsciiDoc_ geschrieben
und mit _Asciidoctor {asciidoctor-version}_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder
auf einem anderem Weg durchgeführt werden können. +
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


== Vorraussetzungen
Die Installation wird für {ubuntu-url}[Ubuntu 18.04 LTS (Bionic Beaver)] beschrieben. +
Gleichwohl sind die einzelnen Schritte auch für
andere Debian-basierte GNU/Linux Distributionen übertragbar.

[TIP]
====
Ubuntu 18.04 LTS (Bionic Beaver) enthält die Pakete::
  _openjdk-8-jdk_8u191-b12-0ubuntu0.18.04.1_amd64.deb_ +
  _openjdk-11-jdk-10.0.2+13-1ubuntu0.18.04.1.deb_

Wenn Sie keine eigenen Programme in _Java_ entwickeln wollen,
reicht die Installation +
des Pakets _openjdk-11-jre_ (_Java Runtime Environment_) vollkommen aus.

[options="nowrap"]
----
$ COLUMNS=132 dpkg --list | grep openjdk-   <1> <2>
ii  openjdk-11-jdk:amd64        10.0.2+13-1ubuntu0 amd64   OpenJDK Development Kit (JDK)
ii  openjdk-11-jdk-headless:amd 10.0.2+13-1ubuntu0 amd64   OpenJDK Development Kit (JDK) (headless)
ii  openjdk-11-jre:amd64        10.0.2+13-1ubuntu0 amd64   OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd 10.0.2+13-1ubuntu0 amd64   OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-8-jre:amd64         8u191-b12-0ubuntu0 amd64   OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd6 8u191-b12-0ubuntu0 amd64   OpenJDK Java runtime, using Hotspot JIT (headless)
----
<1> COLUMNS=96 ist eine Formatangabe für die Ausgabe von #dpkg#
<2> *openjdk-8-...* und *openjdk-11-...* kann bereits durch _andere_ Abhängigkeiten installiert sein!
====


== Wahlmöglichkeiten
.OpenJDK 8/11 .vs Oracle JDK 8/11
Öffentliche Updates für Oracle Java SE 8 (SE -- Standard Edition)
enden in 2020 für Privatnutzer -- wobei die Versionen 9 sowie 10
bereits ausgelaufen sind bzw. aus dem Support herausfallen. +
Das kommende Java SE 11 wird erst gar nicht im öffentlichen Support
verfügbar sein. Für Firmen ist ab Januar 2019 eine kommerzielle Nutzerlizenz
(für Oracle Java SE 8) erforderlich, um Updates einsetzen zu dürfen. +

Für Java steht eine gute OpenSource-Anwendung zur Verfügung: das _OpenJDK 8/11_.
Sie sind erhältlich in den regulären
Ubuntu-Repositories und erhalten regelmäßig Sicherheits-Updates.
Für viele Menschen ist dieses Java ausreichend.

Für *JRuby* ist ein Java 8-compatibles (oder höher) Java development kit (JDK)
Vorraussetzung.

[NOTE]
====
Unabhängig davon, das die Firma _Oracle_ das freie _OpenJDK_ unterstützt und auch
vorantreibt ... gibt es durchaus Bugs, die in den proprietären Paketen nicht
vorhanden sind. +
Es gilt, Bugs zu melden, damit _OpenJDK_ ebenso gut wird.
====

[NOTE]
====
OpenJDK 8/11 ist aktuell und für alle Ubuntu-Versionen verfügbar.
Wer kann, sollte sich für OpenJDK 11 entscheiden -
Java 11 ist (wie zuletzt Java 8) eine Long-Term-Support (LTS) Version.
Das Ende des Supports für Java 11 ist noch nicht bekannt.

&rarr; http://wiki.ubuntuusers.de/Java[ubunutusers.de: Java]
====


== Installation: OpenJDK 11
[options="nowrap"]
----
$ sudo apt install openjdk-11-jdk  <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
openjdk-11-jdk ist schon die neueste Version (10.0.2+13-1ubuntu0.18.04.4).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
----
<1> Vielleicht ist das Paket bei Ihnen wie bei mir bereits installiert ;-)

----
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
----




include::_bp_footer.adoc[]
