IiU -- OpenJDK 7, Oracle JDK 7
==============================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by/4.0/deed.de
:mit-url:             http://opensource.org/licenses/mit-license.php  
:ubuntu-url:          http://www.ubuntu.com/
:asciidoctor-url:     http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:git-url:             http://git-scm.com/
:git-download-url:    https://www.kernel.org/pub/software/scm/git/

:ruby-url:            https://www.ruby-lang.org/de/
:ruby-download-url:   https://www.ruby-lang.org/de/downloads/
:rubyonrails-url:     http://www.rubyonrails.org

:java-url:            http://www.oracle.com/technetwork/java/javase/downloads/index.html

:java-koerper-url:    http://www.arndt-bruenner.de/mathe/java/koerper3d.htm

Version 3.2.0, Mai 2015


Abstract
--------
Dieser Artikel ist eine Schritt-für-Schritt Anleitung zur Installation 
eines _Java Development Kit (JDK)_ unter _GNU/Linux_.
 
Der Artikel ist in {asciidoctordocs-url}[AsciiDoc] geschrieben 
und mit _Asciidoctor {asciidoctor-version}_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzungen
----------------
Die Installation wird für {ubuntu-url}[Ubuntu 14.04 LTS (Trusty Tahr)] 
beschrieben. +
Gleichwohl sind die einzelnen Schritte auch für 
andere Debian-basierte GNU/Linux Distributionen übertragbar.

[TIP]
====
In Ubuntu 14.04 LTS (Trusty Tahr) kann über bestehende Abhängigkeiten +
zu anderen Ubuntu-Paketen bereits das _OpenJDK 7_ installiert sein.

[options="nowrap"]
----
$ dpkg --list | grep openjdk 
ii  openjdk-7-jdk:amd64            7u79-2.5.5-0ubuntu0.14.04.2   amd64   OpenJDK Development Kit (JDK)
ii  openjdk-7-jre:amd64            7u79-2.5.5-0ubuntu0.14.04.2   amd64   OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-7-jre-headless:amd64   7u79-2.5.5-0ubuntu0.14.04.2   amd64   OpenJDK Java runtime, using Hotspot JIT (headless)
----
====


Wahlmöglichkeiten
-----------------
.OpenJDK 7 .vs Oracle JDK 7
Für Java steht eine gute OpenSource-Anwendung zur Verfügung: das _OpenJDK 7_ und
das _IcedTea-Plugin_ für den Browser. Sie sind erhältlich in den regulären 
Ubuntu-Repositories und erhalten regelmäßig Sicherheits-Updates.
Für viele Menschen ist dieses Java ausreichend.

Das ist mit ein Grund warum das ClosedSource Oracle Java von den offiziellen
Software-Repositories entfernt wurde. 

Ein weiterer Grund war natürlich auch, das Oracle die 
_Operating System Distributor License for Java (DLJ)_ zurückgezog.

&rarr; http://sites.google.com/site/easylinuxtipsproject/java#TOC-Primary-choice:-OpenJDK-6-and-not-Oracle-Sun-Java[Oracle (Sun) Java JRE for Ubuntu, Linux Mint and Debian]

[NOTE]
====
Unabhängig davon, das die Firma _Oracle_ das freie _JDK_ unterstützt und auch
vorantreibt ... gibt es durchaus Bugs, die in den propietären Paketen nicht 
vorhanden sind. +
Es gilt, Bugs zu melden, damit _OpenJDK_ ebenso gut wird.
====

[NOTE]
====
OpenJDK 7 ist aktuell, aber im Gegensatz zum Vorgänger nicht für alle 
Ubuntu-Versionen verfügbar. Wer kann, sollte sich für OpenJDK 7 entscheiden - 
solange ein spezieller Anwendungszweck wie beispielsweise _ElsterOnline_ nicht 
dagegen spricht.

&rarr; http://wiki.ubuntuusers.de/Java[ubunutusers.de: Java]
====


Installation: OpenJDK 7
-----------------------

----
$ sudo apt-get -s install icedtea-7-plugin  <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  icedtea-netx icedtea-netx-common
Die folgenden NEUEN Pakete werden installiert:
  icedtea-7-plugin icedtea-netx icedtea-netx-common
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
[...]
----    
<1> Sie müssen entscheiden ob Sie das Java-Plugin für den Browser installieren, 
    oder aus Sicherheitsgründen darauf verzichten...!?
    
----
$ sudo apt-get install openjdk-7-jdk  <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
openjdk-7-jdk ist schon die neueste Version.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
----    
<1> Vielleicht ist das Paket bei Ihnen wie bei mir bereits installiert ;-)

----
$ java -version
java version "1.7.0_79"   
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0~14.04.02)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
----   

 
Installation: Oracle JDK 7
--------------------------
Wie auch immer, einige Ubuntu-Anwender benötigen das Oracle JDK. +
Empfohlen wird die jeweils neueste Version - zu diesem Zeitpunkt ist das: 
_Java SE Development Kit 7u79_.

Zusätzliche Software-Pakete  
sollten im Verzeichnis `/opt` &nbsp; (Optional) installiert werden. 

*Step 0:* Download JDK 7u79

&rarr; {java-url}[Oracle: Java SE Downloads]

[NOTE]
====
You must accept the Oracle Binary Code License Agreement 
for Java SE to download this software.
====

*Step 1:* Installation im Verzeichnis `/opt/Java` &nbsp; (mit Benutzer 'root')
----
$ sudo mkdir /opt/Java
$ sudo mv jdk-7u79-linux-x64.tar.gz /opt/Java  
$ cd /opt/Java 

$ ls -l
-rw-rw-r-- 1 sid sid  154773078 Mai  8 21:34 jdk-7u79-linux-i586.tar.gz

$ sudo tar xvzf jdk-7u79-linux-x64.tar.gz
...
----

Ein Vorteil bei der gezeigten Lösung ist, daß für das Einspielen einer neuen Version 
weder die Konfigurations-Datei noch die +PATH+-Variable angepasst werden müssen.  
----
$ sudo chown -R root.root jdk1.7.0_79

$ sudo ln -s jdk1.7.0_79 current
$ ls -l
lrwxrwxrwx 1 root root        11 Mai  8 21:42 current -> jdk1.7.0_79
-rw-r--r-- 1 root root       328 Mär  3  2014 java.path.sh
drwxr-xr-x 8 root root      4096 Apr 10 20:53 jdk1.7.0_79
-rw-rw-r-- 1 sid  sid  153512879 Mai  8 21:41 jdk-7u79-linux-x64.tar.gz

----

*Step 2:* Java-Pfad setzen (von au&szlig;en)
Erstellen Sie eine Datei `java.path.sh` (siehe <<_anhang,[Anhang]>>). 
[NOTE] 
=========================================================
Achtung: Ausführen der Datei mit dem Punkt-Operator!
----
$ . java.path.sh
---- 
=========================================================

*Step 3:* Installation verifizieren
---- 
$ which java
/opt/Java/current/bin/java

$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)   <1>
----
<1> _b_ steht für _build_


Java im Browser
---------------
Überprüfen Sie die im Browser installierten _Plugins_:

* Mozilla Firefox +
  +about:plugins+ 
* Chromium +
  +chrome://plugins/+

Beide Browser greifen bei mir auf das _IcedTea-Web Plugin_ zu: +
+IcedTea-Web Plugin (using IcedTea-Web 1.5 (1.5-1ubuntu1))+

+++ <br /> +++
  
Mit den folgenden Links können Sie zum Einen die im Browser verwendete
Java-Version bestimmen, zum Anderem die Funktionsfähigkeit des Plugin
überprüfen oder -- halt die aktuelle Zeit anzeigen:

* http://www.arndt-bruenner.de/mathe/java/[Testseiten für Java-Applets - von Arndt Brünner] +
  Platonische und Archimedische Körper (mein Favorit ;-)
* http://www.w3.org/2000/07/8378/object/java/clock[W3C: Java applet test with applet and object] +
  W3C host clocks: MIT, UTC, INRIA, Keio
* http://javatester.org/[Java Tester] +
  Test the version of Java your browser is using
  
[CAUTION]
====
.[Java Tester] NEW SECURITY IN JAVA 7 UPDATE 51: January 27, 2014.
Update 51 changed the default security rules for unsigned Java applets such as 
the one on this page. +
By default, Java no longer runs any unsigned applets. [...]  
====

+++ <br /> +++

Darüberhinaus sollten Sie die Hinweise zur Sicherheit von Browsern überhaupt 
und die mit _Java_ im Besonderen immer im Blick haben... + 

* http://www.heise.de/security/hilfe/[heise Security: Erste Hilfe] +
  *Browsercheck*: Java, JavaScript/JScript, Visual Basic Script, ActiveX,
  Cookies, XPI-Erweiterungen, Phishing
  

Anhang
------
Script zum Setzen der Umgebung für das Oracle JDK (ohne weitere Erläuterung).

.Datei: `java.path.sh`
----
JAVA_BINDIR=/opt/Java/current/bin
JAVA_HOME=/opt/Java/current
JDK_HOME=/opt/Java/current
JRE_HOME=/opt/Java/current

PATH=$JAVA_BINDIR:$PATH

export JAVA_BINDIR
export JAVA_HOME
export JDK_HOME
export JRE_HOME
export PATH
----

