IiU -- Rails 4.2: Erste Schritte &hellip; mit JRuby 
===================================================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by/4.0/deed.de
:mit-url:             http://opensource.org/licenses/mit-license.php  
:ubuntu-url:          http://www.ubuntu.com/
:asciidoctor-url:     http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:git-url:             http://git-scm.com/
:git-download-url:    https://www.kernel.org/pub/software/scm/git/

:java-url:            http://www.oracle.com/technetwork/java/javase/downloads/index.html
:jruby-url:           http://jruby.org/
:jruby-download-url:  http://jruby.org/download

:jdk-url:             link:jdk.html
:jruby-version:       1.7.16

Version 3.0.0, September 2014


Abstract
--------
Die folgenden Schritte stellen die Funktionsfähigkeit der Installation 
von _JRuby_ und _Ruby on Rails_ (kurz: _Rails_) sicher. 

Der Artikel ist in {asciidoctordocs-url}[AsciiDoc] geschrieben 
und mit _Asciidoctor 1.5.1_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzungen
----------------
_JRuby_ und _Ruby on Rails_ sind wie in

* {jruby-url}[Installation in Ubuntu: JRuby 1.7.16, Rails 4.2]
 
beschrieben durchgeführt worden.

.JRuby 1.7.16
----
$ which jruby
/opt/JRuby/sid/current/bin/jruby

$ jruby -v 
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on OpenJDK 64-Bit Server VM 1.7.0_65-b32 +jit [linux-amd64]

$ which rails
/opt/JRuby/sid/current/bin/rails

$ jruby -S rails -v   <1>
Rails 4.2.0.beta1

$ rails -v     <2>
Rails 4.2.0.beta1
----
<1> Der Schalter _-S_ führt dazu, daß für das Script zuerst  
    das Verzeichnis +JRUBY_HOME/bin+ geprüft wird - und
    dann der +PATH+.
<2> Solange wie die ausführbaren Programme von _JRuby on Rails_ im +PATH+ vorangestellt
    werden, kann auf _jruby -S_ verzichtet werden.       


Erste Schritte &hellip;
-----------------------
Die notwendigen Schritte werden auf der Kommandozeile durchgeführt.

.Vorgehensweise 
- Datenbanksystem wählen 
- Datenbank erstellen
- Projektverzeichnis erstellen 
- Datenbankadapter konfigurieren
- JavaScript-Runtime installieren
- Aufruf der Webanwendung im Browser


Datenbanksystem wählen
----------------------
Für _Ruby on Rails_ sind drei Datenbanksysteme zumindest erste Wahl für
die Entwicklung eines neuen Rails-Projektes:

- _SqLite3_ + 
  Ist in _Ruby on Rails_ die Default-Datenbank.
- _MySQL_ +
  Gut und schnell und überhaupt ... überall verfügbar.
- _PostgreSQL_ +
  Lupenreine OpenSource-Datenbanksystem für professionelle Anforderungen. +
  (Ähnliches Vorgehen wie mit MySQL.)

Für die Datenbanksysteme _SqLite3_ und _MySQL_ sind die notwendigen Datenbankadapter
bereits installiert worden.
 

Datenbank erstellen
-------------------
_SQLite3_ ist eine Programmbibliothek, die ein relationales Datenbanksystem enthält.
Das bedeutet, der normale Aufwand an Administration für ein Datenbanksystem, sowie
für das Anlegen von Benutzern, einer Datenbank und dem Zuweisen von Rechten entfällt. 

_MySQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _phpMyAdmin_ ... aber eben auch
die Kommandozeile.

_PostgreSQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _pgAdmin_ ... aber eben auch
die Kommandozeile.

.Anlegen eines Benutzer: _sid_ (in MySQL)
----
# mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 77
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL PRIVILEGES ON *.* to 'sid'@'localhost'
    -> IDENTIFIED BY 'GEHEIM';
Query OK, 0 rows affected (0.00 sec)

mysql> exit  
----

.Erstellen einer Datenbank: _jmyapp_development_ (in MySQL)
----
$ mysql -usid -p 
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 78
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE jmyapp_development;
Query OK, 1 row affected (0.00 sec)

mysql> exit
Bye
----


Projektverzeichnis erstellen 
----------------------------
----
$ cd
$ mkdir RailsDir

$ cd RailsDir
$ rails _4.2.0.beta1_ new jMyApp --database=mysql   <1>
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile      <2>
      create  app
      create  app/assets/javascripts/application.js
 [...]
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
[...]
      create  config/database.yml   <3>
      create  db
      create  db/seeds.rb      
[...]
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies.....
Using rake 10.3.2
Using i18n 0.7.0.beta1
Using json 1.8.1
Using minitest 5.4.2
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0.beta1
Using builder 3.2.2
Using erubis 2.7.0
Using rails-deprecated_sanitizer 1.0.3
Using nokogiri 1.6.3.1
Using rails-dom-testing 1.0.3
Using actionview 4.2.0.beta1
Using rack 1.6.0.beta
Using rack-test 0.6.2
Using actionpack 4.2.0.beta1
Using mime-types 2.3
Using mail 2.6.1
Using actionmailer 4.2.0.beta1
Using globalid 0.3.0
Using activejob 4.2.0.beta1
Using activemodel 4.2.0.beta1
Using arel 6.0.0.beta1
Using activerecord 4.2.0.beta1
Using activerecord-jdbc-adapter 1.3.10   <4>
Using jdbc-mysql 5.1.31
Using activerecord-jdbcmysql-adapter 1.3.10   <5>
Using bundler 1.7.3
Installing coffee-script-source 1.8.0
Installing execjs 2.2.1
Installing coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0.beta1
Installing coffee-rails 4.0.1
Using hike 1.2.3
Using multi_json 1.10.1
Installing jbuilder 2.1.3
Installing jquery-rails 3.1.2
Installing loofah 2.0.1
Using tilt 1.4.1
Using sprockets 2.12.2
Using sprockets-rails 3.0.0.beta1
Using rails 4.2.0.beta1
Installing rails-html-sanitizer 1.0.1
Using rdoc 4.1.2
Installing sass 3.4.5
Installing sass-rails 5.0.0.beta1
Installing sdoc 0.4.1
Installing therubyrhino_jar 1.7.4
Installing therubyrhino 2.0.4
Installing turbolinks 2.3.0
Installing uglifier 2.5.3
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> Für das Datenbanksystem _SqLite3_ verkürzt sich der Aufruf: 
    _rails new myapp_
<2> Die zu diesem Zeitpunkt benötigten RubyGems und deren Abhängigkeiten
    untereinander entnehmen Sie der Datei _Gemfile_.
<3> Konfigurationsdatei mit den Einstellungen für den 
    Datenbankzugriff (Datenbankadapter).        
<4> Im Netz gibt es möglicherweise aktuell _neuere_ Versionen für den 
    Zugriff mit _Java_ ...
<5> ...auf die Datenbank _MySQL_.
    
.Datei: +Gemfile+
----
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0.beta1'
# Use jdbcmysql as the database for Active Record
gem 'activerecord-jdbcmysql-adapter'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.0.beta1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'   <1>
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyrhino'   <2>
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Rails Html Sanitizer for HTML sanitization
gem 'rails-html-sanitizer', '~> 1.0'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
end
----
<1> Der Spezifizierer '~> 4.0.0' ist identisch mit 
    den Bedingungen '>= 4.0.0' und '< 4.1'.  
<2> RubyGem _therubyrhino_: JavaScript-Interpreter      
 
.Prüfen der Abhängigkeiten im +Gemfile+
----
$ cd jMyApp

$ bundle check  
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 khk khk 1232 Sep 28 23:52 Gemfile
-rw-rw-r-- 1 khk khk 3996 Sep 28 23:53 Gemfile.lock
----


Datenbankadapter konfigurieren
------------------------------
.config/database.yml: sqlite3
----
[...]
development:
  adapter: sqlite3
  database: db/development.sqlite3   <1>
[...]
----
<1> Die Datenbank-Datei wird mit dem ersten Aufruf automatisch angelegt. +
    Keine Angabe für Benutzer und Passwort!

.Datei: +config/database.yml+ mysql 
----
[...]
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: sid                 <---          
  password: GEHEIM              <---
  socket: /var/run/mysqld/mysqld.sock

development:   <1>
  <<: *default
  database: myapp_development   <2>
[...]  
----
<1> Es werden ausschließlich die zu _default_ geänderten Einträge aufgeführt.
<2> Der hier vorgeschlagene Datenbank-Name wird von _Ruby on Rails_
    automatisch aus dem Namen der Applikation und dem Zusatz '_development'
    gebildet.


JavaScript-Runtime installieren
-------------------------------
Für die erzeugte _Ruby on Rails_-Anwendung ist eine JavaScript-Runtime erforderlich.

.Möglichkeit 1: Das RubyGem _therubyrhino_

link:http://rubygems.org/gems/therubyrhino[RubyGems.org: therubyrhino] +
Embed the Mozilla Rhino JavaScript interpreter into Ruby. +
(Ist bereits installiert ... siehe oben:) 
  
.Möglichkeit 2: Das Ubuntu-Paket 'nodejs' installieren
----
$ sudo apt-get -s install nodejs       <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libc-ares2 libv8-3.14.5
Die folgenden NEUEN Pakete werden installiert:
  libc-ares2 libv8-3.14.5 nodejs
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
Inst libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Inst libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Inst nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
Conf libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Conf libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Conf nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
----
<1> _apt-get -s ... (simulate)_ ich habe mich dagegen entschieden.


Aufruf der Webanwendung im Browser
----------------------------------
WEBrick wird in _Ruby on Rails_ default-mäßig als Testserver für die 
Entwicklungs-Umgebung verwendet.

----
$ rails s 
=> Booting WEBrick
=> Rails 4.2.0.beta1 application starting in development on http://localhost:3000   <1>
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2014-09-29 00:01:32] INFO  WEBrick 1.3.1
[2014-09-29 00:01:32] INFO  ruby 1.9.3 (2014-09-25) [java]   <2>
[2014-09-29 00:01:32] INFO  WEBrick::HTTPServer#start: pid=26551 port=3000
----
<1> Der Webserver läuft ohne Port-Angabe (_--port_ ...) auf Port 3000.
<2> Ruby Version 1.9.3

----
Browser> http://localhost:3000/   <1>
         About your application’s environment   <2>       
----
<1> Grundsätzlicher Test der Verbindung!
<2> Link zu weiteren Informationen...

----
Browser> http://localhost:3000/rails/info/properties/   <1>
----
<1> Informationen zur ausgeführten Applikation _MyApp_: + 
   (Ruby-Version, RubyGems, Verzeichnis, Umgebung, Datenbank, Datenbank-Schema)

oder 

----
$ rake about  
----

.Ausgabe...
----
About your application's environment
Ruby version              1.9.3-p392 (java)   <1>
RubyGems version          2.2.2
Rack version              1.5
Rails version             4.2.0.beta1
JavaScript Runtime        therubyrhino (Rhino)
Active Record version     4.2.0.beta1
Action Pack version       4.2.0.beta1
Action View version       4.2.0.beta1
Action Mailer version     4.2.0.beta1
Active Support version    4.2.0.beta1
Active Model version      4.2.0.beta1
Middleware                Rack::Sendfile, 
                          ActionDispatch::Static, 
                          Rack::Lock, 
                          #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x...>, 
                          Rack::Runtime, 
                          Rack::MethodOverride, 
                          ActionDispatch::RequestId, 
                          Rails::Rack::Logger, 
                          ActionDispatch::ShowExceptions, 
                          ActionDispatch::DebugExceptions, 
                          ActionDispatch::RemoteIp, 
                          ActionDispatch::Reloader, 
                          ActionDispatch::Callbacks, 
                          ActiveRecord::Migration::CheckPending, 
                          ActiveRecord::ConnectionAdapters::ConnectionManagement, 
                          ActiveRecord::QueryCache, 
                          ActionDispatch::Cookies, 
                          ActionDispatch::Session::CookieStore, 
                          ActionDispatch::Flash, 
                          ActionDispatch::ParamsParser, 
                          Rack::Head, 
                          Rack::ConditionalGet, 
                          Rack::ETag
Application root          /home/sid/RailsDir/jMyApp
Environment               development
Database adapter          mysql2
Database schema version   0
----
<1> Ruby Version 1.9.3 (java)


Anhang
------
Abschließend die Liste der aktuell installierten _RubyGems_.

----
$ gem list --local

*** LOCAL GEMS ***

actionmailer (4.2.0.beta1)
actionpack (4.2.0.beta1)
actionview (4.2.0.beta1)
activejob (4.2.0.beta1)
activemodel (4.2.0.beta1)
activerecord (4.2.0.beta1)
activerecord-jdbc-adapter (1.3.10)
activerecord-jdbcmysql-adapter (1.3.10)
activerecord-jdbcsqlite3-adapter (1.3.10)
activesupport (4.2.0.beta1)
arel (6.0.0.beta1)
asciidoctor (1.5.1)
axiom-types (0.1.1)
builder (3.2.2)
bundler (1.7.3)
coercible (1.0.0)
coffee-rails (4.0.1)
coffee-script (2.3.0)
coffee-script-source (1.8.0)
descendants_tracker (0.0.4)
equalizer (0.0.9)
erubis (2.7.0)
execjs (2.2.1)
ffi (1.9.5 java, 1.9.3 java)
globalid (0.3.0)
hike (1.2.3)
i18n (0.7.0.beta1)
ice_nine (0.11.0)
jar-dependencies (0.1.2)
jbuilder (2.1.3)
jdbc-mysql (5.1.31)
jdbc-sqlite3 (3.7.15.SNAPSHOT)
jquery-rails (3.1.2)
jruby-jars (1.7.16)
jruby-openssl (0.9.5 java)
jruby-rack (1.1.16)
json (1.8.1 java, 1.8.0 java)
krypt (0.0.2)
krypt-core (0.0.2 universal-java)
krypt-provider-jdk (0.0.2)
loofah (2.0.1)
mail (2.6.1)
maven-tools (1.0.5)
mime-types (2.3)
minitest (5.4.2)
multi_json (1.10.1)
nokogiri (1.6.3.1 java)
rack (1.6.0.beta)
rack-protection (1.5.3)
rack-test (0.6.2)
rails (4.2.0.beta1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.3)
rails-html-sanitizer (1.0.1)
railties (4.2.0.beta1)
rake (10.3.2, 10.1.0)
rdoc (4.1.2, 4.0.1)
rdoc-data (4.0.1)
ruby-maven (3.1.1.0.8)
ruby-maven-libs (3.1.1)
rubygems-update (2.4.1, 2.2.2)
rubyzip (1.1.6)
sass (3.4.5)
sass-rails (5.0.0.beta1)
sdoc (0.4.1)
sinatra (1.4.5)
sprockets (2.12.2)
sprockets-rails (3.0.0.beta1)
therubyrhino (2.0.4)
therubyrhino_jar (1.7.4)
thor (0.19.1)
thread_safe (0.3.4 java)
tilt (1.4.1)
turbolinks (2.3.0)
tzinfo (1.2.2)
uglifier (2.5.3)
virtus (1.0.3)
warbler (1.4.4)
----


