IiU -- JRuby on Rails 4.2: Erste Schritte &hellip; 
==================================================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by/4.0/deed.de
:mit-url:             http://opensource.org/licenses/mit-license.php  
:ubuntu-url:          http://www.ubuntu.com/
:asciidoctor-url:     http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:git-url:             http://git-scm.com/
:git-download-url:    https://www.kernel.org/pub/software/scm/git/
:ruby-url:            https://www.ruby-lang.org/de/
:ruby-download-url:   https://www.ruby-lang.org/de/downloads/
:rubyonrails-url:     http://www.rubyonrails.org

:java-url:            http://www.oracle.com/technetwork/java/javase/downloads/index.html
:jruby-url:           http://jruby.org/
:jruby-download-url:  http://jruby.org/download

:jdk-url:             link:jdk.html
:jruby-version:       1.7.18

Version 3.0.4, Dezember 2014


Abstract
--------
Die folgenden Schritte stellen die Funktionsfähigkeit der Installation 
von {jruby-url}[JRuby] und {rubyonrails-url}[Ruby on Rails] (kurz: _Rails_) sicher. 

Der Artikel ist in {asciidoctordocs-url}[AsciiDoc] geschrieben 
und mit _Asciidoctor {asciidoctor-version}_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzungen
----------------
_JRuby_ und _Ruby on Rails_ sind wie in

* {jruby-url}[IiU -- JRuby 1.7.18, rails-4.2.0]
 
beschrieben durchgeführt worden.

.JRuby 1.7.18
----
$ which jruby
/opt/JRuby/sid/current/bin/jruby

$ jruby -v 
jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on OpenJDK 64-Bit Server VM 1.7.0_65-b32 +jit [linux-amd64]

$ which rails
/opt/JRuby/sid/current18/bin/rails

$ jruby -S rails -v   <1>
Rails 4.2.0

$ rails -v     <2>
Rails 4.2.0
----
<1> Der Schalter #-S# führt dazu, daß für das Script zuerst  
    das Verzeichnis `${JRUBY_HOME}/bin` geprüft wird - und
    dann der +PATH+.
<2> Solange wie die ausführbaren Programme von _JRuby on Rails_ im +PATH+ vorangestellt
    werden, kann auf #jruby -S# verzichtet werden.       


Erste Schritte &hellip;
-----------------------
Die notwendigen Schritte werden auf der Kommandozeile durchgeführt.

.Vorgehensweise 
- Datenbanksystem wählen 
- Datenbankadapter installieren
- Datenbank erstellen
- Projektverzeichnis erstellen 
- Datenbankadapter konfigurieren
- JavaScript-Runtime installieren
- Warbler installieren
- Aufruf der Webanwendung im Browser


Datenbanksystem wählen
~~~~~~~~~~~~~~~~~~~~~~
Für das Framework *Ruby on Rails* sind die folgenden drei Datenbanksysteme zumindest 
für die _Entwicklung_ (aber auch für die _Produktion_) eines neuen 
*Rails*-Projektes die erste Wahl:

- _SqLite3_ +
  Klein, kompakt und dateibasiert – mit diesen Vorzügen glänzt 'SQLite3'. + 
  Ist in _Ruby on Rails_ die Default-Datenbank.
- _MySQL_ +
  Gut und schnell und überhaupt ... überall verfügbar.
- _PostgreSQL_ +
  Lupenreine OpenSource-Datenbanksystem für professionelle Anforderungen. 
  
[CAUTION]
====
Die einzelnen Schritte für die Datenbank *PostgreSQL* werden 
in diesem Artikel nicht beschrieben. +
In der Vorgehensweise sind sie ähnlich derer für *MySQL*
====
 

Datenbankadapter installieren
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.Datenbankzugriff (via JDBC)
----
$ gem install activerecord-jdbc-adapter --no-rdoc --no-ri
Fetching: activerecord-jdbc-adapter-1.3.13.gem (100%)
Successfully installed activerecord-jdbc-adapter-1.3.13
1 gem installed
----

.MySQL
----
$ gem install activerecord-jdbcmysql-adapter --no-rdoc --no-ri
Fetching: jdbc-mysql-5.1.33.gem (100%)
Successfully installed jdbc-mysql-5.1.33
Fetching: activerecord-jdbcmysql-adapter-1.3.13.gem (100%)
Successfully installed activerecord-jdbcmysql-adapter-1.3.13
2 gems installed
----

.SQLite3
----
Fetching: jdbc-sqlite3-3.8.7.gem (100%)
Successfully installed jdbc-sqlite3-3.8.7
Fetching: activerecord-jdbcsqlite3-adapter-1.3.13.gem (100%)
Successfully installed activerecord-jdbcsqlite3-adapter-1.3.13
2 gems installed
----

----
$ gem list --local | grep jdbc
activerecord-jdbc-adapter (1.3.13)
activerecord-jdbcmysql-adapter (1.3.13)
activerecord-jdbcsqlite3-adapter (1.3.13)
jdbc-mysql (5.1.33)
jdbc-sqlite3 (3.8.7)
----


Datenbank erstellen
~~~~~~~~~~~~~~~~~~~
_SQLite3_ ist eine Programmbibliothek, die ein relationales Datenbanksystem enthält.
Das bedeutet, der normale Aufwand an Administration für ein Datenbanksystem, sowie
für das Anlegen von Benutzern, einer Datenbank und dem Zuweisen von Rechten entfällt. 

_MySQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _phpMyAdmin_ ... aber eben auch
die Kommandozeile.

.Anlegen eines Benutzer: _sid_ (in MySQL)
----
$ mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 78
Server version: 5.5.40-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL PRIVILEGES ON *.* to 'sid'@'localhost'
    -> IDENTIFIED BY 'g3h3im';
Query OK, 0 rows affected (0.00 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)

mysql> exit
Bye
----

.Erstellen einer Datenbank: _jmyapp_development_ (in MySQL)
----
$ mysql -usid -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 80
Server version: 5.5.40-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE jmyapp_develpment;
Query OK, 1 row affected (0.00 sec)

mysql> exit
Bye
----


Projektverzeichnis erstellen 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
----
$ cd
$ mkdir RailsDir

$ cd RailsDir
$ rails _4.2.0_ new jMyApp --database=mysql   <1> <2>
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile      <3>
      create  app
      create  app/assets/javascripts/application.js
 [...]
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
[...]
      create  config/database.yml   <4>
      create  db
      create  db/seeds.rb      
[...]
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies....
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.1
Using minitest 5.5.0
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using nokogiri 1.6.5
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.2
Using actionpack 4.2.0
Using globalid 0.3.0
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using activerecord-jdbc-adapter 1.3.13   <5>
Using jdbc-mysql 5.1.33
Using activerecord-jdbcmysql-adapter 1.3.13   <6>
Using bundler 1.7.9
Installing coffee-script-source 1.8.0
Installing execjs 2.2.2
Installing coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0
Installing coffee-rails 4.1.0
Using hike 1.2.3
Using multi_json 1.10.1
Installing jbuilder 2.2.6
Installing jquery-rails 4.0.2
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.2
Using rails 4.2.0
Using rdoc 4.2.0
Installing sass 3.4.9
Installing sass-rails 5.0.0
Installing sdoc 0.4.1
Installing therubyrhino_jar 1.7.4
Installing therubyrhino 2.0.4
Installing turbolinks 2.5.3
Installing tzinfo-data 1.2014.10
Installing uglifier 2.6.0
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> #_4.2.0_# -- Festlegen, welche Rails-Version verwendet werden soll. +
    #--database=mysql# -- Festlegen, welches DBMS verwendet werden soll.
<2> Für das Datenbanksystem _SQLite3_ verkürzt sich der Aufruf: +
    #rails _4.2.0_ new myapp#
<3> Die zu diesem Zeitpunkt benötigten RubyGems und deren Abhängigkeiten
    untereinander entnehmen Sie der Datei `Gemfile`.
<4> Konfigurationsdatei mit den Einstellungen für den 
    Datenbankzugriff (Datenbankadapter).        
<5> Im Netz gibt es möglicherweise aktuell _neuere_ Versionen für den 
    Zugriff mit _Java_ ...
<6> ...auf die Datenbank _MySQL_.
    
----
$ cd jMyApp
$ tree -LF 1 .
.
├── app/
│   ├── assets/
│   ├── controllers/
│   ├── helpers/
│   ├── mailers/
│   ├── models/
│   └── views/
├── bin/
│   ├── bundle*
│   ├── rails*
│   ├── rake*
│   └── setup*
├── config/
│   ├── application.rb
│   ├── boot.rb
│   ├── database.yml
│   ├── environment.rb
│   ├── environments/
│   ├── initializers/
│   ├── locales/
│   ├── routes.rb
│   └── secrets.yml
├── config.ru
├── db/
│   └── seeds.rb
├── Gemfile        <1>
├── Gemfile.lock
├── lib/
│   ├── assets/
│   └── tasks/
├── log/
├── public/
│   ├── 404.html
│   ├── 422.html
│   ├── 500.html
│   ├── favicon.ico
│   └── robots.txt
├── Rakefile
├── README.rdoc
├── test/
│   ├── controllers/
│   ├── fixtures/
│   ├── helpers/
│   ├── integration/
│   ├── mailers/
│   ├── models/
│   └── test_helper.rb
├── tmp/
│   └── cache/
└── vendor/
    └── assets/

29 directories, 22 files
----
<1> Datei: `Gemfile` 
    
.Datei: `Gemfile`
----
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use jdbcmysql as the database for Active Record
gem 'activerecord-jdbcmysql-adapter'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'   <1>
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyrhino'   <2>
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
----
<1> Twiddle Waka '~> 4.1.0' ist identisch mit 
    den Bedingungen '>= 4.1.0' und '< 4.2'.  
<2> RubyGem _therubyrhino_: JavaScript-Interpreter      
 
.Prüfen der Abhängigkeiten im +Gemfile+
----
$ bundle check  
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 sid sid 1268 Dez 23 18:50 Gemfile
-rw-rw-r-- 1 sid sid 3911 Dez 23 18:51 Gemfile.lock
----


Datenbankadapter konfigurieren
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.config/database.yml: sqlite3
----
[...]
development:
  adapter: sqlite3
  database: db/development.sqlite3   <1>
[...]
----
<1> Die Datenbank-Datei wird mit dem ersten Aufruf automatisch angelegt. +
    Keine Angabe für Benutzer und Passwort!

.Datei: +config/database.yml+ mysql 
----
[...]
default: &default
  adapter: mysql
  encoding: utf8
  pool: 5
  username: sid                 <---          
  password: g3h3im              <---
  socket: /var/run/mysqld/mysqld.sock

development:   <1>
  <<: *default
  database: jmyapp_development   <2>
[...]  
----
<1> Es werden ausschließlich die zu _default_ geänderten Einträge aufgeführt.
<2> Der hier vorgeschlagene Datenbank-Name wird von _Ruby on Rails_
    automatisch gebildet: +
    Name der Applikation 'MyApp' und dem Zusatz '_development'


JavaScript-Runtime installieren
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Für die erzeugte _Ruby on Rails_-Anwendung ist eine JavaScript-Runtime erforderlich.

.Möglichkeit 1: Das RubyGem _therubyrhino_

-> http://rubygems.org/gems/therubyrhino[RubyGems.org: therubyrhino] +
Embed the Mozilla Rhino JavaScript interpreter into Ruby. +
(Ist bereits installiert ... siehe oben:) 
  
.Möglichkeit 2: Das Ubuntu-Paket 'nodejs' installieren
----
$ sudo apt-get -s install nodejs       <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libc-ares2 libv8-3.14.5
Die folgenden NEUEN Pakete werden installiert:
  libc-ares2 libv8-3.14.5 nodejs
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
Inst libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Inst libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Inst nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
Conf libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Conf libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Conf nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
----
<1> _apt-get -s ... (simulate)_ ich habe mich dagegen entschieden.


Warbler installieren
~~~~~~~~~~~~~~~~~~~~
*Warbler* chirpily constructs `.war` files of your Ruby applications. +
-> https://github.com/jruby/warbler[GitHub: jruby / warbler]  

.WAR (WAR ist ein Dateiformat und steht für Web Application Archive) 
----
$ gem install warbler --no-rdoc --no-ri
Fetching: rubyzip-1.1.6.gem (100%)
Successfully installed rubyzip-1.1.6
Fetching: jruby-rack-1.1.16.gem (100%)
Successfully installed jruby-rack-1.1.16
Fetching: jruby-jars-1.7.18.gem (100%)     <1>
Successfully installed jruby-jars-1.7.18
Fetching: warbler-1.4.4.gem (100%)
Successfully installed warbler-1.4.4
4 gems installed
----
<1> *jruby-jars 1.7.18* includes the core JRuby code and the 
    JRuby 1.8/1.9 stdlib as jar files. It provides a way to have 
    other gems depend on JRuby without including (and freezing to) 
    a specific jruby-complete jar version.


Aufruf der Webanwendung im Browser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WEBrick wird in _Ruby on Rails_ default-mäßig als Testserver für die 
Entwicklungs-Umgebung verwendet.

----
$ jruby bin/rails s 
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000   <1>
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2014-12-23 19:06:40] INFO  WEBrick 1.3.1
[2014-12-23 19:06:40] INFO  ruby 1.9.3 (2014-12-22) [java]   <2>
[2014-12-23 19:06:40] INFO  WEBrick::HTTPServer#start: pid=7729 port=3000
...
----
<1> Der Webserver läuft ohne Port-Angabe (_--port_ ...) auf Port 3000.
<2> Ruby Version 1.9.3

----
Browser> http://localhost:3000/   <1>
         About your application’s environment   <2>       
----
<1> Grundsätzlicher Test der Verbindung!
<2> Link zu weiteren Informationen...

----
Browser> http://localhost:3000/rails/info/properties/   <1>
----
<1> Informationen zur ausgeführten Applikation _MyApp_: + 
   (Ruby-Version, RubyGems, Verzeichnis, Umgebung, Datenbank, Datenbank-Schema)

oder 

----
$ rake about  
About your application's environment
Rails version        4.2.0
Ruby version         1.9.3-p551 (java)   <1>
RubyGems version     2.4.5
Rack version         1.5
JavaScript Runtime   therubyrhino (Rhino)
Middleware           Rack::Sendfile, 
                     ActionDispatch::Static, 
                     Rack::Lock, 
                     #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x...>, 
                     Rack::Runtime, 
                     Rack::MethodOverride, 
                     ActionDispatch::RequestId, 
                     Rails::Rack::Logger, 
                     ActionDispatch::ShowExceptions, 
                     ActionDispatch::DebugExceptions, 
                     ActionDispatch::RemoteIp, 
                     ActionDispatch::Reloader, 
                     ActionDispatch::Callbacks, 
                     ActiveRecord::Migration::CheckPending, 
                     ActiveRecord::ConnectionAdapters::ConnectionManagement, 
                     ActiveRecord::QueryCache, 
                     ActionDispatch::Cookies, 
                     ActionDispatch::Session::CookieStore, 
                     ActionDispatch::Flash, 
                     ActionDispatch::ParamsParser, 
                     Rack::Head, 
                     Rack::ConditionalGet, 
                     Rack::ETag
Application root     /home/sid/RailsDir/jMyApp
Environment          development
Database adapter     mysql

----
<1> Ruby Version 1.9.3 (java)


Anhang
------
Abschließend die Liste der aktuell installierten _RubyGems_.

----
$ gem list --local

*** LOCAL GEMS ***

actionmailer (4.2.0)
actionpack (4.2.0)
actionview (4.2.0)
activejob (4.2.0)
activemodel (4.2.0)
activerecord (4.2.0)
activerecord-jdbc-adapter (1.3.13)
activerecord-jdbcmysql-adapter (1.3.13)
activerecord-jdbcsqlite3-adapter (1.3.13)
activesupport (4.2.0)
arel (6.0.0)
asciidoctor (1.5.2)
axiom-types (0.1.1)
builder (3.2.2)
bundler (1.7.9)
coderay (1.1.0)
coercible (1.0.0)
coffee-rails (4.1.0)
coffee-script (2.3.0)
coffee-script-source (1.8.0)
descendants_tracker (0.0.4)
equalizer (0.0.9)
erubis (2.7.0)
execjs (2.2.2)
ffi (1.9.6 java, 1.9.3 java)
globalid (0.3.0)
hike (1.2.3)
i18n (0.7.0)
ice_nine (0.11.1)
jar-dependencies (0.1.7, 0.1.2)
jbuilder (2.2.6)
jdbc-mysql (5.1.33)
jdbc-sqlite3 (3.8.7)
jquery-rails (4.0.2)
jruby-jars (1.7.18)
jruby-openssl (0.9.6 java, 0.9.5 java)
jruby-rack (1.1.16)
json (1.8.1 java, 1.8.0 java)
krypt (0.0.2)
krypt-core (0.0.2 universal-java)
krypt-provider-jdk (0.0.2)
loofah (2.0.1)
mail (2.6.3)
maven-tools (1.0.7)
mime-types (2.4.3)
minitest (5.5.0)
multi_json (1.10.1)
nokogiri (1.6.5 java)
rack (1.6.0)
rack-protection (1.5.3)
rack-test (0.6.2)
rails (4.2.0)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.5)
rails-html-sanitizer (1.0.1)
railties (4.2.0)
rake (10.4.2, 10.1.0)
rdoc (4.2.0, 4.1.2)
rdoc-data (4.0.1)
ruby-maven (3.1.1.0.8)
ruby-maven-libs (3.1.1)
rubygems-update (2.4.5)
rubyzip (1.1.6)
sass (3.4.9)
sass-rails (5.0.0)
sdoc (0.4.1)
sinatra (1.4.5)
sprockets (2.12.3)
sprockets-rails (2.2.2)
therubyrhino (2.0.4)
therubyrhino_jar (1.7.4)
thor (0.19.1)
thread_safe (0.3.4 java)
tilt (1.4.1)
turbolinks (2.5.3)
tzinfo (1.2.2)
tzinfo-data (1.2014.10)
uglifier (2.6.0)
virtus (1.0.3)
warbler (1.4.4)
----




'''
 
+++
<a href="#top" title="zum Seitenanfang">
  <span>&#8679;</span> 
</a>
+++
[small]#&middot; Document generated with Asciidoctor {asciidoctor-version}.#

