IiU -- Rails 4: Erste Schritte &hellip; mit JRuby 
=================================================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by-sa/3.0/de/
:ubuntu-url: http://www.ubuntu.com/
:asciidoctor-url: http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:jruby-url: link:jruby.html


Version 2.2.0, März 2014


Abstract
--------
Die folgenden Schritte stellen die Funktionsfähigkeit der Installation 
von _JRuby_ und _Ruby on Rails_ (kurz: _Rails_) sicher. 

Der Artikel ist in {asciidoctordocs-url}[AsciiDoc] geschrieben 
und mit _Asciidoctor 1.5.0.preview3_ erstellt worden.

[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzungen
----------------
_JRuby_ und _Ruby on Rails_ sind wie in

* {jruby-url}[Installation in Ubuntu: JRuby 1.7.11, Ruby on Rails 4.0.3]
 
beschrieben durchgeführt worden.

.JRuby 1.7.11
----
$ which jruby
/opt/JRuby/sid/current/bin/jruby

$ jruby -v 
jruby 1.7.11 (1.9.3p392) 2014-02-24 86339bb on OpenJDK 64-Bit Server VM 1.7.0_51-b00 [linux-amd64]

$ jruby -v --2.0   <1> 
jruby 1.7.11 (2.0.0p195) 2014-02-24 86339bb on OpenJDK 64-Bit Server VM 1.7.0_51-b00 [linux-amd64]

$ which rails
/opt/JRuby/sid/current/bin/rails

$ jruby -S rails -v   <2>
Rails 4.0.3

$ rails -v     <3>
Rails 4.0.3
----
<1> Die Installation _JRuby_ enthält zwei (gleichberechtigte) Implementationen der 
    Programmier-Sprache _Ruby_: +
    _Ruby 1.9.3-p392_ (default) +
    _Ruby 2.0.0-p195_ +
    _Ruby 1.8.7-p370_ kann für _Rails 4_ nicht mehr verwendet werden!
<2> Der Schalter _-S_ führt dazu, daß für das Script zuerst  
    das Verzeichnis +JRUBY_HOME/bin+ geprüft wird - und
    dann der +PATH+.
<3> Solange wie die ausführbaren Programme von _JRuby on Rails_ im +PATH+ vorangestellt
    werden, kann auf _jruby -S_ verzichtet werden.       


Erste Schritte &hellip;
-----------------------
Die notwendigen Schritte werden auf der Kommandozeile durchgeführt.

.Vorgehensweise 
- Datenbanksystem wählen 
- Datenbank erstellen
- Projektverzeichnis erstellen 
- Datenbankadapter konfigurieren
- JavaScript-Runtime installieren
- Aufruf der Webanwendung im Browser


Datenbanksystem wählen
----------------------
Für _Ruby on Rails_ sind drei Datenbanksysteme zumindest erste Wahl für
die Entwicklung eines neuen Rails-Projektes:

- _SqLite3_ + 
  Ist in _Ruby on Rails_ die Default-Datenbank.
- _MySQL_ +
  Gut und schnell und überhaupt ... überall verfügbar.
- _PostgreSQL_ +
  Lupenreine OpenSource-Datenbanksystem für professionelle Anforderungen. +
  (Ähnliches Vorgehen wie mit MySQL.)

Für die Datenbanksysteme _SqLite3_ und _MySQL_ sind die notwendigen Datenbankadapter
bereits installiert worden.
 

Datenbank erstellen
-------------------
_SQLite3_ ist eine Programmbibliothek, die ein relationales Datenbanksystem enthält.
Das bedeutet, der normale Aufwand an Administration für ein Datenbanksystem, sowie
für das Anlegen von Benutzern, einer Datenbank und dem Zuweisen von Rechten entfällt. 

_MySQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _phpMyAdmin_ ... aber eben auch
die Kommandozeile.

_PostgreSQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _pgAdmin_ ... aber eben auch
die Kommandozeile.

.Anlegen eines Benutzer: _sid_ (in MySQL)
----
# mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 77
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL PRIVILEGES ON *.* to 'sid'@'localhost'
    -> IDENTIFIED BY 'GEHEIM';
Query OK, 0 rows affected (0.00 sec)

mysql> exit  
----

.Erstellen einer Datenbank: _jmyapp_development_ (in MySQL)
----
$ mysql -usid -p 
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 78
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE jmyapp_development;
Query OK, 1 row affected (0.00 sec)

mysql> exit
Bye
----


Projektverzeichnis erstellen 
----------------------------
----
$ cd
$ mkdir RailsDir

$ cd RailsDir
$ rails new jMyApp --database=mysql   <1>
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile      <2>
      create  app
      create  app/assets/javascripts/application.js
 [...]
      create  config/database.yml   <3>
      create  db
      create  db/seeds.rb      
 [...]
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies....
Using rake 10.1.1
Using i18n 0.6.9
Using minitest 4.7.5
Using multi_json 1.8.4
Using atomic 1.1.15
Using thread_safe 0.2.0
Using tzinfo 0.3.38
Using activesupport 4.0.3
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.0.3
Using mime-types 1.25.1
Using polyglot 0.3.4
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 4.0.3
Using activemodel 4.0.3
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.2
Using activerecord 4.0.3
Using activerecord-jdbc-adapter 1.3.6   <4>
Using jdbc-mysql 5.1.28
Using activerecord-jdbcmysql-adapter 1.3.6   <5>
Using bundler 1.6.0.rc
Installing coffee-script-source 1.7.0
Installing execjs 2.0.2
Installing coffee-script 2.2.0
Using thor 0.18.1
Using railties 4.0.3
Installing coffee-rails 4.0.1
Using hike 1.2.3
Installing jbuilder 1.5.3
Installing jquery-rails 3.1.0
Using json 1.8.1
Using tilt 1.4.1
Using sprockets 2.11.0
Using sprockets-rails 2.0.1
Using rails 4.0.3
Using rdoc 4.1.1
Installing sass 3.2.14
Installing sass-rails 4.0.1
Installing sdoc 0.4.0
Installing therubyrhino_jar 1.7.4
Installing therubyrhino 2.0.3
Installing turbolinks 2.2.1
Installing uglifier 2.4.0
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> Für das Datenbanksystem _SqLite3_ verkürzt sich der Aufruf: 
    _rails new myapp_
<2> Die zu diesem Zeitpunkt benötigten RubyGems und deren Abhängigkeiten
    untereinander entnehmen Sie der Datei _Gemfile_.
<3> Konfigurationsdatei mit den Einstellungen für den 
    Datenbankzugriff (Datenbankadapter).        
<4> Im Netz gibt es möglicherweise aktuell _neuere_ Versionen für den 
    Zugriff mit _Java_ ...
<5> ...auf die Datenbank _MySQL_.
    
.Datei: +Gemfile+
----
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.3'

# Use jdbcmysql as the database for Active Record
gem 'activerecord-jdbcmysql-adapter'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'   <1>

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyrhino'   <2>

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development
----
<1> Der Spezifizierer '~> 4.0.0' ist identisch mit 
    den Bedingungen '>= 4.0.0' und '< 4.1'.  
<2> RubyGem _therubyrhino_: JavaScript-Interpreter      
 
.Prüfen der Abhängigkeiten im +Gemfile+
----
$ cd jMyApp

$ bundle check  
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 sid sid 1119 Mär  3 18:47 Gemfile
-rw-rw-r-- 1 sid sid 3061 Mär  3 18:48 Gemfile.lock
----

[NOTE]
====
_CoffeeScript_ ist seit _Ruby on Rails_ v3.1 Standard.
====


Datenbankadapter konfigurieren
------------------------------
.config/database.yml: sqlite3
----
[...]
development:
  adapter: sqlite3
  database: db/development.sqlite3   <1>
[...]
----
<1> Die Datenbank-Datei wird mit dem ersten Aufruf automatisch angelegt. +
    Keine Angabe für Benutzer und Passwort!

.config/database.yml: mysql 
----
[...]
development:
  adapter: mysql
  database: jmyapp_development   <1>
  username: sid
  password: GEHEIM
  host: localhost
[...]  
----
<1> Der hier vorgeschlagene Datenbank-Name wird von _Ruby on Rails_
    automatisch aus dem Namen der Applikation und dem Zusatz '_development'
    gebildet.


JavaScript-Runtime installieren
-------------------------------
Für die erzeugte _Ruby on Rails_-Anwendung ist eine JavaScript-Runtime erforderlich.

.Möglichkeit 1: Das RubyGem _therubyrhino_

link:http://rubygems.org/gems/therubyrhino[RubyGems.org: therubyrhino] +
Embed the Mozilla Rhino JavaScript interpreter into Ruby. +
(Ist bereits installiert ... siehe oben:) 
  
.Möglichkeit 2: Das Ubuntu-Paket 'nodejs' installieren
----
$ sudo apt-get install nodejs
Abhängigkeitsbaum wird aufgebaut       
Statusinformationen werden eingelesen... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libc-ares2 libev4 libv8-3.7.12.22
Die folgenden NEUEN Pakete werden installiert:
  libc-ares2 libev4 libv8-3.7.12.22 nodejs
0 aktualisiert, 4 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 2.099 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 6.400 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren [J/n]? 
[...]
nodejs (0.6.12~dfsg1-1ubuntu1) wird eingerichtet ...
update-alternatives: /usr/bin/node wird verwendet, um /usr/bin/js (js) im Auto-Modus bereitzustellen.
Trigger für libc-bin werden verarbeitet ...
ldconfig deferred processing now taking place
----


Aufruf der Webanwendung im Browser
----------------------------------
WEBrick wird in _Ruby on Rails_ default-mäßig als Testserver für die 
Entwicklungs-Umgebung verwendet.

----
$ rails s 
=> Booting WEBrick
=> Rails 4.0.3 application starting in development on http://0.0.0.0:3000   <1>
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2014-03-03 18:52:55] INFO  WEBrick 1.3.1
[2014-03-03 18:52:55] INFO  ruby 1.9.3 (2014-02-24) [java]                   <2>
[2014-03-03 18:52:55] INFO  WEBrick::HTTPServer#start: pid=14412 port=3000
----
<1> Der Webserver läuft ohne Port-Angabe (_--port_ ...) auf Port 3000.
<2> Ruby Version 1.9.3

----
Browser> http://localhost:3000/   <1>
         About your application’s environment   <2>       
----
<1> Grundsätzlicher Test der Verbindung!
<2> Link zu weiteren Informationen...

----
Browser> http://localhost:3000/rails/info/properties/   <1>
----
<1> Informationen zur ausgeführten Applikation _MyApp_: + 
   (Ruby-Version, RubyGems, Verzeichnis, Umgebung, Datenbank, Datenbank-Schema)

oder 

----
$ rake about  
----

.Ausgabe...
----
About your application's environment
Ruby version              1.9.3 (java)   <1>
RubyGems version          2.2.2
Rack version              1.5
Rails version             4.0.3
JavaScript Runtime        therubyrhino (Rhino)
Active Record version     4.0.3
Action Pack version       4.0.3
Action Mailer version     4.0.3
Active Support version    4.0.3
Middleware                Rack::Sendfile, 
                          ActionDispatch::Static, 
                          Rack::Lock, 
                          #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0...>, 
                          Rack::Runtime, 
                          Rack::MethodOverride, 
                          ActionDispatch::RequestId, 
                          Rails::Rack::Logger, 
                          ActionDispatch::ShowExceptions, 
                          ActionDispatch::DebugExceptions, 
                          ActionDispatch::RemoteIp, 
                          ActionDispatch::Reloader, 
                          ActionDispatch::Callbacks, 
                          ActiveRecord::Migration::CheckPending, 
                          ActiveRecord::ConnectionAdapters::ConnectionManagement, 
                          ActiveRecord::QueryCache, 
                          ActionDispatch::Cookies, 
                          ActionDispatch::Session::CookieStore, 
                          ActionDispatch::Flash, 
                          ActionDispatch::ParamsParser, 
                          Rack::Head, 
                          Rack::ConditionalGet, 
                          Rack::ETag
Application root	        /home/sid/80/RailsDir/jMyApp
Environment	              development
Database adapter	        mysql
Database schema version	  0
----
<1> Ruby Version 1.9.3 (java)


Anhang
------
Abschließend die Liste der aktuell installierten _RubyGems_.

----
$ gem list --local

*** LOCAL GEMS ***

actionmailer (4.0.3)
actionpack (4.0.3)
activemodel (4.0.3)
activerecord (4.0.3)
activerecord-deprecated_finders (1.0.3)
activerecord-jdbc-adapter (1.3.6)
activerecord-jdbcmysql-adapter (1.3.6)
activerecord-jdbcsqlite3-adapter (1.3.6)
activesupport (4.0.3)
arel (4.0.2)
asciidoctor (1.5.0.preview3)
atomic (1.1.15 java)
bouncy-castle-java (1.5.0147)
builder (3.1.4)
bundler (1.6.0.rc)
coffee-rails (4.0.1)
coffee-script (2.2.0)
coffee-script-source (1.7.0)
erubis (2.7.0)
execjs (2.0.2)
hike (1.2.3)
i18n (0.6.9)
jbuilder (1.5.3)
jdbc-mysql (5.1.28)
jdbc-sqlite3 (3.7.15.SNAPSHOT)
jquery-rails (3.1.0)
jruby-jars (1.7.11)
jruby-openssl (0.9.4, 0.9.3)
jruby-rack (1.1.14)
json (1.8.1 java, 1.8.0 java)
krypt (0.0.1)
krypt-core (0.0.1 universal-java)
krypt-provider-jdk (0.0.1)
mail (2.5.4)
mime-types (1.25.1)
minitest (4.7.5)
multi_json (1.8.4)
polyglot (0.3.4)
rack (1.5.2)
rack-protection (1.5.2)
rack-test (0.6.2)
rails (4.0.3)
railties (4.0.3)
rake (10.1.1, 10.1.0)
rdoc (4.1.1, 4.0.1)
rdoc-data (4.0.1)
rubygems-update (2.2.2)
rubyzip (1.0.0)
sass (3.2.14)
sass-rails (4.0.1)
sdoc (0.4.0)
sinatra (1.4.4)
sprockets (2.11.0)
sprockets-rails (2.0.1)
therubyrhino (2.0.3)
therubyrhino_jar (1.7.4)
thor (0.18.1)
thread_safe (0.2.0 java)
tilt (1.4.1)
treetop (1.4.15)
turbolinks (2.2.1)
tzinfo (0.3.38)
uglifier (2.4.0)
warbler (1.4.1)
----


