IiU -- Ruby on Rails 4.2
========================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by/4.0/deed.de
:mit-url:             http://opensource.org/licenses/mit-license.php  
:ubuntu-url:          http://www.ubuntu.com/
:asciidoctor-url:     http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:git-url:             http://git-scm.com/
:git-download-url:    https://www.kernel.org/pub/software/scm/git/

:ruby-url:            https://www.ruby-lang.org/de/
:ruby-download-url:   https://www.ruby-lang.org/de/downloads/
:rubyonrails-url:     http://www.rubyonrails.org

:ruby-version:        2.2.4
:ruby19-url:          link:ruby19.html
:ruby21-url:          link:ruby21.html
:ruby22-url:          link:ruby22.html
:ruby23-url:          link:ruby23.html

Version 4.0.0, Januar 2016


Abstract
--------
Die folgenden Schritte stellen die Funktionsfähigkeit der Installation 
von {ruby-url}[Ruby] und {rubyonrails-url}[Ruby on Rails] (kurz: _Rails_) sicher. 

Der Artikel ist in {asciidoctordocs-url}[Asciidoctor] geschrieben 
und mit _Asciidoctor {asciidoctor-version}_ erstellt worden.


[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzung
--------------
Die Installation von *Ruby* und ist, wie in

* {ruby22-url}[IiU -- Ruby 2.2.4]  

oder

* {ruby23-url}[IiU -- Ruby 2.3.0]


beschrieben, durchgeführt worden.

[CAUTION]
====
Die hier aufgeführten Schritte werden beispielhaft für *Ruby 2.2.4* ausgeführt.

Gelten aber, auch in dieser Reihenfolge, ebenfalls für die *Ruby-Versionen >= 1.9.3*.

Eine Installation von *Ruby on Rails 5.0* ist nur mit *Ruby-Versionen >= 2.2* möglich!
==== 

.Ruby 2.2.4
----
$ which ruby
/opt/Ruby/current22/bin/ruby

$ ruby -v 
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
----


RubyGem: rails-4.2.5
--------------------
*Step 0* 
----
$ gem search ^rails$ --remote

*** REMOTE GEMS ***

rails (4.2.5)   <1>
----
<1> Seit dem 12.11.2015 ist das die neueste Version des RubyGem _rails_. 

[TIP]
====
Die Installation der Dokumentation kann ausgelassen werden.
----
$ sudo su -
# . /opt/Ruby/ruby22.path.sh
# gem install rails --no-rdoc --no-ri   <1>
---- 
<1> #- -no-rdoc - -no-ri# &nbsp; In der Regel wird die offizielle Dokumentation genutzt: +
    -> http://guides.rubyonrails.org/ 
====

Mit #gem install ...# werden auch alle Abhängigkeiten zu anderen RubyGems aufgelöst.
---- 
# gem install rails --no-rdoc --no-ri
Fetching: concurrent-ruby-1.0.0.gem (100%)
Successfully installed concurrent-ruby-1.0.0
...
Fetching: rails-4.2.5.gem (100%)
Successfully installed rails-4.2.5
30 gems installed   <1>
----
<1> Mit dem RubyGem _rails-4.2.5_ wurden insgesamt 30 Gems installiert. +
    Hinweis: Weitere RubyGems müssen für das Framework *Ruby on Rails* installiert werden. 

[NOTE]
====
Alternativ kann das RubyGem _rails_ mit der Angabe einer Version installiert werden.
----
# gem install rails --version 4.1.14

# gem install rails --version '~> 4.1.14'   <1>
----
<1> Twiddle Wakka: '~> 4.1.14' bedeutet, das die höchste Gem-Version von Rails +
    im Bereich von >= 4.1.14 und < 4.2 installiert wird. 
====


Ruby on Rails 4.2.5
-------------------
Die notwendigen Schritte werden auf der Kommandozeile durchgeführt.

.Vorgehensweise 
- Datenbanksystem wählen 
- Datenbankadapter installieren
- Datenbank erstellen
- Projektverzeichnis erstellen 
- Datenbankadapter konfigurieren
- JavaScript-Runtime installieren
- Aufruf der Webanwendung im Browser


Datenbanksystem wählen
~~~~~~~~~~~~~~~~~~~~~~
Für das Framework *Ruby on Rails* sind die folgenden drei Datenbanksysteme zumindest 
für die _Entwicklung_ (aber auch für die _Produktion_) eines neuen 
*Rails*-Projektes die erste Wahl:

- _SqLite3_ +
  Klein, kompakt und dateibasiert – mit diesen Vorzügen glänzt 'SQLite3'. + 
  Ist in _Ruby on Rails_ die Default-Datenbank.
- _MySQL_ +
  Gut und schnell und überhaupt ... überall verfügbar.
- _PostgreSQL_ +
  Lupenreine OpenSource-Datenbanksystem für professionelle Anforderungen. 
  
[CAUTION]
====
Die einzelnen Schritte für die Datenbank *PostgreSQL* werden 
in diesem Artikel nicht beschrieben. +
In der Vorgehensweise sind sie ähnlich derer für *MySQL*
====


Datenbankadapter installieren
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---- 
# gem install mysql2 --no-rdoc --no-ri
Fetching: mysql2-0.4.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed mysql2-0.4.2
1 gem installed
----

----
# gem install sqlite3 --no-rdoc --no-ri  
Fetching: sqlite3-1.3.11.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sqlite3-1.3.11
1 gem installed
----


Datenbank erstellen
~~~~~~~~~~~~~~~~~~~
_SQLite3_ ist eine Programmbibliothek, die ein relationales Datenbanksystem enthält.
Das bedeutet, der notwendige Aufwand an Administration für ein Datenbanksystem, sowie
für das Anlegen von Benutzern, einer Datenbank und dem Zuweisen von Rechten entfällt. 

_MySQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _phpMyAdmin_ ... aber eben auch
die Kommandozeile.

.Anlegen eines Benutzer: _sid_ (in MySQL)
----
$ mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 79
Server version: 5.5.46-0ubuntu0.14.04.2 (Ubuntu)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL PRIVILEGES ON *.* to 'sid'@'localhost'
    -> IDENTIFIED BY 'g3h3im';
Query OK, 0 rows affected (0.00 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)

mysql> exit
Bye
----

.Erstellen einer Datenbank: _myapp_development_ (in MySQL)
----
$ mysql -usid -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 79
Server version: 5.5.46-0ubuntu0.14.04.2 (Ubuntu)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE myapp_develpment;
Query OK, 1 row affected (0.00 sec)

mysql> exit
Bye
----


Projektverzeichnis erstellen 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
----
$ cd
$ mkdir RailsDir

$ cd RailsDir
$ rails _4.2.5_ new MyApp --database=mysql -B  <1> <2> <3>
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile      <4>
      create  app
      create  app/assets/javascripts/application.js
 ...
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
...
      create  config/database.yml   <5>
      create  db
      create  db/seeds.rb      
...
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
----
<1> #_4.2.5_# -- Festlegen, welche Rails-Version verwendet werden soll. +
    #--database=mysql# -- Festlegen, welches DBMS verwendet werden soll.
<2> Für das Datenbanksystem _SQLite3_ verkürzt sich der Aufruf: +
    #rails _4.2.5_ new myapp#
<3> #-B# Don't run bundle install +
    Kein automatisches 'install' und 'update' von RubyGems!   
<4> Die zu diesem Zeitpunkt benötigten RubyGems und deren Abhängigkeiten
    untereinander entnehmen Sie der Datei `Gemfile`.
<5> Konfigurationsdatei mit den Einstellungen für den 
    Datenbankzugriff (Datenbankadapter).        

----
$ cd MyApp
$ tree -LF 2 .
.
├── app/
│   ├── assets/
│   ├── controllers/
│   ├── helpers/
│   ├── mailers/
│   ├── models/
│   └── views/
├── bin/
│   ├── bundle*
│   ├── rails*
│   ├── rake*
│   └── setup*
├── config/
│   ├── application.rb
│   ├── boot.rb
│   ├── database.yml     <1>
│   ├── environment.rb
│   ├── environments/
│   ├── initializers/
│   ├── locales/
│   ├── routes.rb
│   └── secrets.yml
├── config.ru
├── db/
│   └── seeds.rb
├── Gemfile        <2>
├── lib/
│   ├── assets/
│   └── tasks/
├── log/
├── public/
│   ├── 404.html
│   ├── 422.html
│   ├── 500.html
│   ├── favicon.ico
│   └── robots.txt
├── Rakefile
├── README.rdoc
├── test/
│   ├── controllers/
│   ├── fixtures/
│   ├── helpers/
│   ├── integration/
│   ├── mailers/
│   ├── models/
│   └── test_helper.rb
├── tmp/
│   └── cache/
└── vendor/
    └── assets/

29 directories, 21 files
----
<1> Datei: `config/database.yml`
<2> Datei: `Gemfile`


RubyGems installieren
~~~~~~~~~~~~~~~~~~~~~
.Prüfen der in der Datei `Gemfile` genannten Abhängigkeiten
----
$ bundle check  
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.

$ bundle list   <1>
Could not find gem 'sass-rails (~> 5.0) java' in any of the gem sources listed
in your Gemfile or installed on this machine.
----
<1> Der User 'root' muß die fehlenden Gems installieren

----
$ ls -l Gemfile*
-rw-rw-r-- 1 sid sid 1521 Jan  4 19:56 Gemfile
----

.Datei: `Gemfile`
----
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'   <1>
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'   <2>
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'   <3>

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
----
<1> Twiddle Waka '~> 4.1.0' ist identisch mit 
    den Bedingungen '>= 4.1.0' und '< 4.2'.  
<2> Twiddle Waka '~> 2.0' ist identisch mit 
    den Bedingungen '>= 2.0' und '< 3'.    
<3> Twiddle Waka '~> 3.1.7' ist identisch mit 
    den Bedingungen '>= 3.1.7' und '< 3.2'.    

----
$ sudo su -
[sudo] password for sid:   <1>

# ruby -v                  <2>
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

# exit
----
<1> Annahme: Der User 'sid' besitzt das Recht das System zu administrieren...
<2> Test, das der Benutzer 'root' den entsprechenden Ruby-Pfad gesetzt hat.

.Installation der fehlenden Gems mit dem zur Installation berechtigten User!  
[options="nowrap"]
----
$ bundle install   <1>   
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......
Using rake 10.4.2   <2>
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.3
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types 2.99
Using arel 6.0.3
Installing debug_inspector 0.0.2 with native extensions   <3>
Using bundler 1.11.2
Installing byebug 8.2.1 with native extensions
Installing coffee-script-source 1.10.0
Installing execjs 2.6.0
Using thor 0.19.1
Using concurrent-ruby 1.0.0
Installing multi_json 1.11.2
Using mysql2 0.4.2
Installing sass 3.4.20
Using tilt 2.0.1
Installing spring 1.6.1
Using rdoc 4.2.1
Using tzinfo 1.2.2
Using nokogiri 1.6.7.1
Using rack-test 0.6.3
Using mail 2.6.3
Installing binding_of_caller 0.7.2 with native extensions
Installing coffee-script 2.4.1
Installing uglifier 2.7.2
Using sprockets 3.5.2
Installing sdoc 0.4.1
Using activesupport 4.2.5
Using loofah 2.0.3
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.5
Installing jbuilder 2.4.0
Using rails-html-sanitizer 1.0.2
Using rails-dom-testing 1.0.7
Using activejob 4.2.5
Using activerecord 4.2.5
Using actionview 4.2.5
Using actionpack 4.2.5
Using actionmailer 4.2.5
Using railties 4.2.5
Using sprockets-rails 3.0.0
Installing coffee-rails 4.1.1
Installing jquery-rails 4.0.5
Using rails 4.2.5
Installing sass-rails 5.0.4
Installing web-console 2.2.1
Installing turbolinks 2.5.3
Bundle complete! 12 Gemfile dependencies, 54 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
----     
<1> In *Ubuntu* verfügt der bei der Installation angelegte Benutzer über alle
    Privilegien, um das System zu administrieren, d. h. zu verwalten.
<2> _Using_: Bereits installierte RubyGems
<3> _Installing_: Neu installierte RubyGems    

.Prüfen der Abhängigkeiten im `Gemfile` (2)
----
$ bundle check <1>
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*   <1>
-rw-rw-r-- 1 sid sid 1521 Jan  4 19:56 Gemfile
-rw-rw-r-- 1 sid sid 3908 Jan  4 20:05 Gemfile.lock
----
<1> Als Benutzer 'sid'!


Datenbankadapter konfigurieren
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.Datei: `config/database.yml` -- sqlite3
----
[...]
development:
  adapter: sqlite3
  database: db/development.sqlite3   <1>
  pool: 5
  timeout: 5000
[...]
----
<1> Die Datenbank-Datei wird mit dem ersten Aufruf automatisch angelegt. +
    Keine Angabe für Benutzer und Passwort!

.Datei: `config/database.yml` -- mysql 
----
[...]
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: sid                 <---          
  password: GEHEIM              <---
  socket: /var/run/mysqld/mysqld.sock

development:   <1>
  <<: *default
  database: myapp_development   <2>
[...]  
----
<1> Es werden ausschließlich die zu _default_ geänderten Einträge aufgeführt.
<2> Der hier vorgeschlagene Datenbank-Name wird von _Ruby on Rails_
    automatisch gebildet: +
    Name der Applikation 'MyApp' und dem Zusatz '_development'


JavaScript-Runtime installieren
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Für die erzeugte _Ruby on Rails_-Anwendung ist eine JavaScript-Runtime erforderlich.

.Möglichkeit 1: Das RubyGem _therubyracer_

.Datei: `Gemfile`
----
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby   <1>
[...]
----
<1> Entfernen Sie das Kommentar-Zeichen am Zeilen-Anfang: '#'.

[options="nowrap"]
----
$ bundle check
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.

$ bundle show
Could not find gem 'therubyracer' in any of the gem sources listed in your Gemfile or available on this machine.
----

----
$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.3
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.0.0
Using rack 1.6.4
Using mime-types 2.99
Using arel 6.0.3
Using debug_inspector 0.0.2
Using bundler 1.11.2
Using byebug 8.2.1
Using coffee-script-source 1.10.0
Using execjs 2.6.0
Using thor 0.19.1
Using concurrent-ruby 1.0.0
Using multi_json 1.11.2


Your user account isn't allowed to install to the system Rubygems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to Rubygems using sudo.

  Password: 
Installing libv8 3.16.14.13   <1>
Using mysql2 0.4.2
Installing ref 2.0.0   <1>
Using sass 3.4.20
Using tilt 2.0.1
Using spring 1.6.1
Using rdoc 4.2.1
Using tzinfo 1.2.2
Using nokogiri 1.6.7.1
Using rack-test 0.6.3
Using mail 2.6.3
Using binding_of_caller 0.7.2
Using coffee-script 2.4.1
Using uglifier 2.7.2
Using sprockets 3.5.2
Installing therubyracer 0.12.2 with native extensions   <1>
Using sdoc 0.4.1
Using activesupport 4.2.5
Using loofah 2.0.3
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.5
Using jbuilder 2.4.0
Using rails-html-sanitizer 1.0.2
Using rails-dom-testing 1.0.7
Using activejob 4.2.5
Using activerecord 4.2.5
Using actionview 4.2.5
Using actionpack 4.2.5
Using actionmailer 4.2.5
Using railties 4.2.5
Using sprockets-rails 3.0.0
Using coffee-rails 4.1.1
Using jquery-rails 4.0.5
Using rails 4.2.5
Using sass-rails 5.0.4
Using web-console 2.2.1
Using turbolinks 2.5.3
Bundle complete! 13 Gemfile dependencies, 57 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> _Installing_: Neu installierte RubyGems

----
$ bundle check
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 sid sid 1519 Jan  4 21:11 Gemfile
-rw-rw-r-- 1 sid sid 4025 Jan  4 21:14 Gemfile.lock
----

.Möglichkeit 2: Das Ubuntu-Paket 'nodejs' installieren
----
$ sudo apt-get -s install nodejs       <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libc-ares2 libv8-3.14.5
Die folgenden NEUEN Pakete werden installiert:
  libc-ares2 libv8-3.14.5 nodejs
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
Inst libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Inst libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Inst nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
Conf libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Conf libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Conf nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
----
<1> _apt-get -s ... (simulate)_ ich habe mich dagegen entschieden.


Aufruf der Webanwendung im Browser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WEBrick wird in _Ruby on Rails_ default-mäßig als Testserver für die 
Entwicklungs-Umgebung verwendet.
----
$ rails s
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000   <1>
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2016-01-04 21:17:22] INFO  WEBrick 1.3.1
[2016-01-04 21:17:22] INFO  ruby 2.2.4 (2015-12-16) [x86_64-linux]   <2>
[2016-01-04 21:17:22] INFO  WEBrick::HTTPServer#start: pid=25444 port=3000
...
----
<1> Der Webserver läuft ohne Port-Angabe (_--port_ ...) auf Port 3000.
<2> Ruby Version 2.2.4

----
BROWSER> http://localhost:3000/   <1>
         About your application’s environment   <2>       
----
<1> Grundsätzlicher Test der Verbindung!
<2> Link zu weiteren Informationen...

----
BROWSER> http://localhost:3000/rails/info/properties/   <1>
----
<1> Informationen zur ausgeführten Applikation _MyApp_: + 
   (Ruby-Version, RubyGems, Verzeichnis, Umgebung, Datenbank, Datenbank-Schema)

oder

----
$ rake about
About your application's environment
Rails version             4.2.5
Ruby version              2.2.4-p230 (x86_64-linux)   <1>
RubyGems version          2.5.1
Rack version              1.6.4
JavaScript Runtime        therubyracer (V8)
Middleware                Rack::Sendfile, 
                          ActionDispatch::Static, 
                          Rack::Lock, 
                          #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f88a6d868b0>, 
                          Rack::Runtime, 
                          Rack::MethodOverride, 
                          ActionDispatch::RequestId, 
                          Rails::Rack::Logger, 
                          ActionDispatch::ShowExceptions, 
                          WebConsole::Middleware, 
                          ActionDispatch::DebugExceptions, 
                          ActionDispatch::RemoteIp, 
                          ActionDispatch::Reloader, 
                          ActionDispatch::Callbacks, 
                          ActiveRecord::Migration::CheckPending, 
                          ActiveRecord::ConnectionAdapters::ConnectionManagement, 
                          ActiveRecord::QueryCache, 
                          ActionDispatch::Cookies, 
                          ActionDispatch::Session::CookieStore, 
                          ActionDispatch::Flash, 
                          ActionDispatch::ParamsParser, 
                          Rack::Head, 
                          Rack::ConditionalGet, 
                          Rack::ETag
Application root          /home/sid/RailsDir/MyApp
Environment               development
Database adapter          mysql2
Database schema version   0
----
<1> Ruby Version 2.2.4


Anhang
------
Abschließend die Liste der aktuell installierten _RubyGems_.

----
$ gem list --local   <1>

*** LOCAL GEMS ***

actionmailer (4.2.5)
actionpack (4.2.5)
actionview (4.2.5)
activejob (4.2.5)
activemodel (4.2.5)
activerecord (4.2.5)
activesupport (4.2.5)
arel (6.0.3)
asciidoctor (1.5.3)
bigdecimal (1.2.7, 1.2.6)
binding_of_caller (0.7.2)
builder (3.2.2)
bundler (1.11.2)
byebug (8.2.1)
coderay (1.1.0)
coffee-rails (4.1.1)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
concurrent-ruby (1.0.0)
debug_inspector (0.0.2)
erubis (2.7.0)
execjs (2.6.0)
globalid (0.3.6)
i18n (0.7.0)
io-console (0.4.5, 0.4.3)
jbuilder (2.4.0)
jquery-rails (4.0.5)
json (1.8.3, 1.8.1)
libv8 (3.16.14.13 x86_64-linux)
loofah (2.0.3)
mail (2.6.3)
method_source (0.8.2)
mime-types (2.99)
mini_portile2 (2.0.0)
minitest (5.8.3, 5.4.3)
multi_json (1.11.2)
mysql2 (0.4.2)
nokogiri (1.6.7.1)
power_assert (0.2.6, 0.2.2)
pry (0.10.3)
psych (2.0.17, 2.0.8)
rack (1.6.4)
rack-protection (1.5.3)
rack-test (0.6.3)
rails (4.2.5)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.2)
railties (4.2.5)
rake (10.4.2)
rdoc (4.2.1, 4.2.0)
ref (2.0.0)
rubygems-update (2.5.1)
sass (3.4.20)
sass-rails (5.0.4)
sdoc (0.4.1)
sinatra (1.4.6)
slop (3.6.0)
spring (1.6.1)
sprockets (3.5.2)
sprockets-rails (3.0.0)
sqlite3 (1.3.11)
test-unit (3.1.5, 3.0.8)
therubyracer (0.12.2)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.1)
turbolinks (2.5.3)
tzinfo (1.2.2)
uglifier (2.7.2)
web-console (2.2.1)
----
<1> Anzahl der installierten RubyGems: _71_




'''
 
+++
<a href="#top" title="zum Seitenanfang">
  <span>&#8679;</span> 
</a>
+++
[small]#&middot; Document generated with Asciidoctor {asciidoctor-version}.#

