IiU -- Rails 4: Erste Schritte &hellip; mit Ruby
================================================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by-sa/3.0/de/
:ubuntu-url: http://www.ubuntu.com/
:asciidoctor-url: http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:ruby19-url: link:ruby19.html
:ruby20-url: link:ruby20.html


Version 2.2.0, März 2014


Abstract
--------
Die folgenden Schritte stellen die Funktionsfähigkeit der Installation 
von _Ruby_ und _Ruby on Rails_ (kurz: _Rails_) sicher. 

Der Artikel ist in {asciidoctordocs-url}[AsciiDoc] geschrieben 
und mit _Asciidoctor 1.5.0.preview3_ erstellt worden.


[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzung
--------------
Die Installation von _Ruby_ und _Ruby on Rails_ ist, wie in

* {ruby19-url}[Installation in Ubuntu: Ruby 1.9.3, Ruby on Rails 4] 

oder 

* {ruby20-url}[Installation in Ubuntu: Ruby 2.0.0, Ruby on Rails 4] 

beschrieben, durchgeführt worden.

Die hier aufgeführten Schritte werden beispielhaft für _Ruby 2.0.0_ ausgeführt.
Gelten aber, auch in dieser Reihenfolge, ebenfalls für _Ruby 1.9.3_. 

.Ruby 2.0.0
----
$ which ruby
/opt/Ruby/current20/bin/ruby

$ ruby -v 
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-linux]

$ which rails
/opt/Ruby/current20/bin/rails

$ rails -v    
Rails 4.0.3
----

  
Erste Schritte &hellip;
-----------------------
Die notwendigen Schritte werden auf der Kommandozeile durchgeführt.

.Vorgehensweise 
- Datenbanksystem wählen 
- Datenbank erstellen
- Projektverzeichnis erstellen 
- Datenbankadapter konfigurieren
- JavaScript-Runtime installieren
- Aufruf der Webanwendung im Browser


Datenbanksystem wählen
----------------------
Für _Ruby on Rails_ sind drei Datenbanksysteme zumindest erste Wahl für
die Entwicklung eines neuen Rails-Projektes:

- _SqLite3_ + 
  Ist in _Ruby on Rails_ die Default-Datenbank.
- _MySQL_ +
  Gut und schnell und überhaupt ... überall verfügbar.
- _PostgreSQL_ +
  Lupenreine OpenSource-Datenbanksystem für professionelle Anforderungen. +
  (Ähnliches Vorgehen wie mit MySQL.)

Für die Datenbanksysteme _SqLite3_ und _MySQL_ sind die notwendigen Datenbankadapter
bereits installiert worden.


Datenbank erstellen
-------------------
_SQLite3_ ist eine Programmbibliothek, die ein relationales Datenbanksystem enthält.
Das bedeutet, der notwendige Aufwand an Administration für ein Datenbanksystem, sowie
für das Anlegen von Benutzern, einer Datenbank und dem Zuweisen von Rechten entfällt. 

_MySQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _phpMyAdmin_ ... aber eben auch
die Kommandozeile.

_PostgreSQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _pgAdmin_ ... aber eben auch
die Kommandozeile.

.Anlegen eines Benutzer: _sid_ (in MySQL)
----
# mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 74
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL PRIVILEGES ON *.* to 'sid'@'localhost'
    -> IDENTIFIED BY 'GEHEIM';
Query OK, 0 rows affected (0.00 sec)

mysql> exit  
----

.Erstellen einer Datenbank: _myapp_development_ (in MySQL)
----
$ mysql -usid -p 
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 75
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE myapp_development;
Query OK, 1 row affected (0.00 sec)

mysql> exit
Bye
----


Projektverzeichnis erstellen 
----------------------------
----
$ cd
$ mkdir RailsDir

$ cd RailsDir
$ rails new MyApp --database=mysql   <1>
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile      <2>
      create  app
      create  app/assets/images/rails.png
 [...]
      create  config/database.yml   <3>
      create  db
      create  db/seeds.rb      
 [...]
      create  vendor/plugins
      create  vendor/plugins/.gitkeep
         run  bundle install
         
Your user account isn't allowed to install to the system Rubygems.
You can cancel this installation and run:

    bundle install --path vendor/bundle

to install the gems into ./vendor/bundle/, or you can enter your password
and install the bundled gems to Rubygems using sudo.

Password:   <4> 
----
<1> Für das Datenbanksystem _sqLite3_ verkürzt sich der Aufruf: +
    _rails new myapp_
<2> Die zu diesem Zeitpunkt benötigten RubyGems und deren Abhängigkeiten
    untereinander entnehmen Sie der Datei +Gemfile+.
<3> Konfigurationsdatei mit den Einstellungen für den 
    Datenbankzugriff (Datenbankadapter).        
<4> Wenn Sie nicht berechtigt sind RubyGems zu installieren, müssen Sie 
    die benötigten RubyGems installieren lassen! (Abbruch: [CRTL-C])

----
$ cd MyApp

$ tree -LF 1 .
.
├── app/
├── bin/
├── config/
├── config.ru
├── db/
├── Gemfile
├── lib/
├── log/
├── public/
├── Rakefile
├── README.rdoc
├── test/
├── tmp/
└── vendor/

10 directories, 4 files
----

.Datei: +Gemfile+
----
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.3'

# Use mysql as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'   <1>

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'   <2>

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'   <3>

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
----
<1> Der Spezifizierer '~> 4.0.0' ist identisch mit 
    den Bedingungen '>= 4.0.0' und '< 4.1'.  
<2> Der Spezifizierer '~> 1.2' ist identisch mit 
    den Bedingungen '>= 1.2' und '< 2'.    
<3> Der Spezifizierer '~> 3.1.2' ist identisch mit 
    den Bedingungen '>= 3.1.2' und '< 3.2'.    

.Prüfen der Abhängigkeiten im +Gemfile+ (1)
----
$ bundle check
Resolving dependencies...
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.

$ bundle list
Could not find gem 'sdoc (>= 0) ruby' in the gems available on this machine.
----

.Installation der fehlenden Gems mit dem zur Installation berechtigten User _root_!
----
# cd ~sid/RailsDir/MyApp

# bundle check
Resolving dependencies...
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.

# bundle install    <1>
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.1.1
Using i18n 0.6.9
Installing minitest 4.7.5   <2>
Using multi_json 1.8.4
Using atomic 1.1.15
Using thread_safe 0.2.0
Using tzinfo 0.3.38
Using activesupport 4.0.3
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.0.3
Using mime-types 1.25.1
Using polyglot 0.3.4
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 4.0.3
Using activemodel 4.0.3
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.2
Using activerecord 4.0.3
Using bundler 1.6.0.rc
Installing coffee-script-source 1.7.0   <3>
Installing execjs 2.0.2
Installing coffee-script 2.2.0
Using thor 0.18.1
Using railties 4.0.3
Installing coffee-rails 4.0.1   <3>
Using hike 1.2.3
Installing jbuilder 1.5.3   <3>
Installing jquery-rails 3.1.0
Using json 1.8.1
Using mysql2 0.3.15
Using tilt 1.4.1
Using sprockets 2.11.0
Using sprockets-rails 2.0.1
Using rails 4.0.3
Using rdoc 4.1.1
Installing sass 3.2.14   <3>
Installing sass-rails 4.0.1
Installing sdoc 0.4.0
Installing turbolinks 2.2.1
Installing uglifier 2.4.0
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> Die Ausgabe bezieht sich auf Ruby Version 2.0.0!
<2> Neu installierte Version von _minitest_.
<3> Neu installierte RubyGems.

.Prüfen der Abhängigkeiten im +Gemfile+ (2)
----
$ bundle check
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 sid  sid  1171 Mär  3 15:39 Gemfile
-rw-rw-r-- 1 root root 2850 Mär  3 15:43 Gemfile.lock   <1>
----
<1> Die Rechte an der Datei +Gemfile.lock+ sind durch den Befehl _bundle install_ 
    (als Benutzer 'root') auf den Benutzer 'root' gesetzt!

----
# rm Gemfile.lock
----

----
$ bundle check
Resolving dependencies...
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 sid  sid  1171 Mär  3 15:39 Gemfile
-rw-rw-r-- 1 sid  sid  2850 Mär  3 15:43 Gemfile.lock  
----


Datenbankadapter konfigurieren
------------------------------
.Datei: +config/database.yml+ sqlite3
----
[...]
development:
  adapter: sqlite3
  database: db/development.sqlite3   <1>
  pool: 5
  timeout: 5000
[...]
----
<1> Die Datenbank-Datei wird mit dem ersten Aufruf automatisch angelegt. +
    Keine Angabe für Benutzer und Passwort!

.Datei: +config/database.yml+ mysql 
----
[...]
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myapp_development   <1>
  pool: 5
  username: sid                 <---          
  password: GEHEIM              <---
  socket: /var/run/mysqld/mysqld.sock
[...]  
----
<1> Der hier vorgeschlagene Datenbank-Name wird von _Ruby on Rails_
    automatisch aus dem Namen der Applikation und dem Zusatz '_development'
    gebildet.


JavaScript-Runtime installieren
-------------------------------
Für die erzeugte _Ruby on Rails_-Anwendung ist eine JavaScript-Runtime erforderlich.

.Möglichkeit 1: Das RubyGem _therubyracer_

.Datei: +Gemfile+
----
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

# Use mysql as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby   <1>

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
[...]
----
<1> Entfernen Sie das Kommentar-Zeichen '#'.

.bundle install (mit dem Benutzer _root_)
----
# cd ~sid/80/RailsDir/MyApp

# bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.1.1
Using i18n 0.6.9
Using minitest 4.7.5
Using multi_json 1.8.4
Using atomic 1.1.15
Using thread_safe 0.2.0
Using tzinfo 0.3.38
Using activesupport 4.0.3
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.0.3
Using mime-types 1.25.1
Using polyglot 0.3.4
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 4.0.3
Using activemodel 4.0.3
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.2
Using activerecord 4.0.3
Using bundler 1.6.0.rc
Using coffee-script-source 1.7.0
Using execjs 2.0.2
Using coffee-script 2.2.0
Using thor 0.18.1
Using railties 4.0.3
Using coffee-rails 4.0.1
Using hike 1.2.3
Using jbuilder 1.5.3
Using jquery-rails 3.1.0
Using json 1.8.1
Installing libv8 3.16.14.3   <1>
Using mysql2 0.3.15
Using tilt 1.4.1
Using sprockets 2.11.0
Using sprockets-rails 2.0.1
Using rails 4.0.3
Using rdoc 4.1.1
Installing ref 1.0.5   <1>
Using sass 3.2.14
Using sass-rails 4.0.1
Using sdoc 0.4.0
Installing therubyracer 0.12.1   <1> <2> <3>
Using turbolinks 2.2.1
Using uglifier 2.4.0
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> Neu installierte RubyGems.
<2> link:http://rubygems.org/gems/therubyracer[RubyGems.org: therubyracer] +
    Call JavaScript code and manipulate JavaScript objects from Ruby. +
    Call Ruby code and manipulate Ruby objects from JavaScript.
<3> Das RubyGem 'therubyracer' wird kompiliert!

----
# rm Gemfile.lock

$ bundle check
Resolving dependencies...
The Gemfile's dependencies are satisfied
----

.Möglichkeit 2: Das Ubuntu-Paket 'nodejs' installieren
----
$ sudo apt-get -s install nodejs       <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut       
Statusinformationen werden eingelesen... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libc-ares2 libev4 libv8-3.7.12.22
Die folgenden NEUEN Pakete werden installiert:
  libc-ares2 libev4 libv8-3.7.12.22 nodejs
0 aktualisiert, 4 neu installiert, 0 zu entfernen und 3 nicht aktualisiert.
Inst libc-ares2 (1.7.5-1 Ubuntu:12.04/precise [amd64])
Inst libv8-3.7.12.22 (3.7.12.22-3 Ubuntu:12.04/precise [amd64])
Inst libev4 (1:4.11-1 Ubuntu:12.04/precise [amd64])
Inst nodejs (0.6.12~dfsg1-1ubuntu1 Ubuntu:12.04/precise [amd64])
Conf libc-ares2 (1.7.5-1 Ubuntu:12.04/precise [amd64])
Conf libv8-3.7.12.22 (3.7.12.22-3 Ubuntu:12.04/precise [amd64])
Conf libev4 (1:4.11-1 Ubuntu:12.04/precise [amd64])
Conf nodejs (0.6.12~dfsg1-1ubuntu1 Ubuntu:12.04/precise [amd64])
----
<1> _apt-get -s ... (simulate)_ ich habe mich dagegen entschieden.


Aufruf der Webanwendung im Browser
----------------------------------
WEBrick wird in _Ruby on Rails_ default-mäßig als Testserver für die 
Entwicklungs-Umgebung verwendet.
----
$ rails s
=> Booting WEBrick
=> Rails 4.0.3 application starting in development on http://0.0.0.0:3000   <1>
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2014-03-03 15:43:24] INFO  WEBrick 1.3.1
[2014-03-03 15:43:24] INFO  ruby 2.0.0 (2014-02-24) [x86_64-linux]   <2>
[2014-03-03 15:43:24] INFO  WEBrick::HTTPServer#start: pid=11182 port=3000
[...]
----
<1> Der Webserver läuft ohne Port-Angabe (_--port_ ...) auf Port 3000.
<2> Ruby Version 2.0.0

----
Browser> http://localhost:3000/   <1>
         About your application’s environment   <2>       
----
<1> Grundsätzlicher Test der Verbindung!
<2> Link zu weiteren Informationen...

----
Browser> http://localhost:3000/rails/info/properties/   <1>
----
<1> Informationen zur ausgeführten Applikation _MyApp_: + 
   (Ruby-Version, RubyGems, Verzeichnis, Umgebung, Datenbank, Datenbank-Schema)

oder

----
$ rake about
[...]
----

.Ausgabe...
----
About your application's environment
Ruby version              2.0.0 (x86_64-linux)   <1>
RubyGems version          2.2.2
Rack version              1.5
Rails version             4.0.3
JavaScript Runtime        therubyracer (V8)
Active Record version     4.0.3
Action Pack version       4.0.3
Action Mailer version     4.0.3
Active Support version    4.0.3
Middleware                Rack::Sendfile, 
                          ActionDispatch::Static, 
                          Rack::Lock, 
                          #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x...>, 
                          Rack::Runtime, 
                          Rack::MethodOverride, 
                          ActionDispatch::RequestId, 
                          Rails::Rack::Logger, 
                          ActionDispatch::ShowExceptions, 
                          ActionDispatch::DebugExceptions, 
                          ActionDispatch::RemoteIp, 
                          ActionDispatch::Reloader, 
                          ActionDispatch::Callbacks, 
                          ActiveRecord::Migration::CheckPending, 
                          ActiveRecord::ConnectionAdapters::ConnectionManagement, 
                          ActiveRecord::QueryCache, 
                          ActionDispatch::Cookies, 
                          ActionDispatch::Session::CookieStore, 
                          ActionDispatch::Flash, 
                          ActionDispatch::ParamsParser, 
                          Rack::Head, 
                          Rack::ConditionalGet, 
                          Rack::ETag
Application root          /home/sid/80/RailsDir/MyApp
Environment               development
Database adapter          mysql2
Database schema version   0
----
<1> Ruby Version 2.0.0


Anhang
------
Abschließend die Liste der aktuell installierten _RubyGems_.

----
$ gem list --local

*** LOCAL GEMS ***

actionmailer (4.0.3)
actionpack (4.0.3)
activemodel (4.0.3)
activerecord (4.0.3)
activerecord-deprecated_finders (1.0.3)
activesupport (4.0.3)
arel (4.0.2)
asciidoctor (1.5.0.preview3)
atomic (1.1.15)
bigdecimal (1.2.5, 1.2.0)
builder (3.1.4)
bundler (1.6.0.rc)
coffee-rails (4.0.1)
coffee-script (2.2.0)
coffee-script-source (1.7.0)
erubis (2.7.0)
execjs (2.0.2)
hike (1.2.3)
i18n (0.6.9)
io-console (0.4.2)
jbuilder (1.5.3)
jquery-rails (3.1.0)
json (1.8.1, 1.7.7)
libv8 (3.16.14.3 x86_64-linux)
mail (2.5.4)
mime-types (1.25.1)
minitest (5.3.0, 4.7.5, 4.3.2)
multi_json (1.8.4)
mysql2 (0.3.15)
polyglot (0.3.4)
psych (2.0.4, 2.0.0)
rack (1.5.2)
rack-protection (1.5.2)
rack-test (0.6.2)
rails (4.0.3)
railties (4.0.3)
rake (10.1.1, 0.9.6)
rdoc (4.1.1, 4.0.0)
ref (1.0.5)
rubygems-update (2.2.2)
sass (3.2.14)
sass-rails (4.0.1)
sdoc (0.4.0)
sinatra (1.4.4)
sprockets (2.11.0)
sprockets-rails (2.0.1)
sqlite3 (1.3.9)
test-unit (2.5.5, 2.0.0.0)
therubyracer (0.12.1)
thor (0.18.1)
thread_safe (0.2.0)
tilt (1.4.1)
treetop (1.4.15)
turbolinks (2.2.1)
tzinfo (0.3.38)
uglifier (2.4.0)
----

