IiU -- Rails 4.2: Erste Schritte &hellip; mit Ruby
==================================================
Installation in Ubuntu — khkoether[at]kahweb[dot]de

:icons:
:Author Initials: KHK
:creativecommons-url: http://creativecommons.org/licenses/by/4.0/deed.de
:mit-url:             http://opensource.org/licenses/mit-license.php  
:ubuntu-url:          http://www.ubuntu.com/
:asciidoctor-url:     http://asciidoctor.org/
:asciidoctordocs-url: http://asciidoctor.org/docs/
:git-url:             http://git-scm.com/
:git-download-url:    https://www.kernel.org/pub/software/scm/git/

:ruby-url:            https://www.ruby-lang.org/de/
:ruby-download-url:   https://www.ruby-lang.org/de/downloads/
:rubyonrails-url:     http://www.rubyonrails.org

:ruby-version:        2.1.3
:ruby19-url:          link:ruby19.html
:ruby21-url:          link:ruby20.html

Version 3.0.1, Oktober 2014


Abstract
--------
Die folgenden Schritte stellen die Funktionsfähigkeit der Installation 
von _Ruby_ und _Ruby on Rails_ (kurz: _Rails_) sicher. 

Der Artikel ist in {asciidoctordocs-url}[AsciiDoc] geschrieben 
und mit _Asciidoctor 1.5.1_ erstellt worden.


[CAUTION]
====
Zu beachten ist, dass so ein Dokument zum Einen nie abschliessend 
sein kann, und zum Anderen bestimmte Konfigurationen anders, oder 
auf einem anderem Weg durchgeführt werden können. 
Gerne nehme ich Verbesserungsvorschläge entgegen.

Es gilt wie immer: Verwendung der Anleitung auf eigene Gefahr.
====


Vorraussetzung
--------------
Die Installation von _Ruby_ und _Ruby on Rails_ ist, wie in

* {ruby19-url}[Installation in Ubuntu: Ruby 1.9.3, Rails 4.2] 

oder 

* {ruby21-url}[Installation in Ubuntu: Ruby 2.1.3, Rails 4.2] 

beschrieben, durchgeführt worden.

Die hier aufgeführten Schritte werden beispielhaft für _Ruby 2.1.3_ ausgeführt.
Gelten aber, auch in dieser Reihenfolge, ebenfalls für _Ruby 1.9.3_. 

.Ruby 2.1.3
----
$ which ruby
/opt/Ruby/current21/bin/ruby

$ ruby -v 
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]

$ which rails
/opt/Ruby/current21/bin/rails

$ rails -v    
Rails 4.2.0.beta1
----

  
Erste Schritte &hellip;
-----------------------
Die notwendigen Schritte werden auf der Kommandozeile durchgeführt.

.Vorgehensweise 
- Datenbanksystem wählen 
- Datenbank erstellen
- Projektverzeichnis erstellen 
- Datenbankadapter konfigurieren
- JavaScript-Runtime installieren
- Aufruf der Webanwendung im Browser


Datenbanksystem wählen
----------------------
Für _Ruby on Rails_ sind drei Datenbanksysteme zumindest erste Wahl für
die Entwicklung eines neuen Rails-Projektes:

- _SqLite3_ + 
  Ist in _Ruby on Rails_ die Default-Datenbank.
- _MySQL_ +
  Gut und schnell und überhaupt ... überall verfügbar.
- _PostgreSQL_ +
  Lupenreine OpenSource-Datenbanksystem für professionelle Anforderungen. +
  (Ähnliches Vorgehen wie mit MySQL.)

Für die Datenbanksysteme _SqLite3_ und _MySQL_ sind die notwendigen Datenbankadapter
bereits installiert worden.


Datenbank erstellen
-------------------
_SQLite3_ ist eine Programmbibliothek, die ein relationales Datenbanksystem enthält.
Das bedeutet, der notwendige Aufwand an Administration für ein Datenbanksystem, sowie
für das Anlegen von Benutzern, einer Datenbank und dem Zuweisen von Rechten entfällt. 

_MySQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _phpMyAdmin_ ... aber eben auch
die Kommandozeile.

_PostgreSQL_ hat für die Administration des Datenbanksystems 
verschiedene Programm-Angebote, unter anderem _pgAdmin_ ... aber eben auch
die Kommandozeile.

.Anlegen eines Benutzer: _sid_ (in MySQL)
----
# mysql -uroot -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 74
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> GRANT ALL PRIVILEGES ON *.* to 'sid'@'localhost'
    -> IDENTIFIED BY 'GEHEIM';
Query OK, 0 rows affected (0.00 sec)

mysql> exit  
----

.Erstellen einer Datenbank: _myapp_development_ (in MySQL)
----
$ mysql -usid -p 
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 75
Server version: 5.5.35-0ubuntu0.12.04.2 (Ubuntu)

Copyright (c) 2000, 2013, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE myapp_development;
Query OK, 1 row affected (0.00 sec)

mysql> exit
Bye
----


Projektverzeichnis erstellen 
----------------------------
----
$ cd
$ mkdir RailsDir

$ cd RailsDir
$ rails _4.2.0.beta1_ new MyApp --database=mysql   <1>
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile      <2>
      create  app
      create  app/assets/javascripts/application.js
 [...]
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
[...]
      create  config/database.yml   <3>
      create  db
      create  db/seeds.rb      
 [...]
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install

         
Your user account isn't allowed to install to the system Rubygems.
You can cancel this installation and run:

    bundle install --path vendor/bundle

to install the gems into ./vendor/bundle/, or you can enter your password
and install the bundled gems to Rubygems using sudo.

Password:   <4> 
----
<1> Für das Datenbanksystem _sqLite3_ verkürzt sich der Aufruf: +
    _rails _4.2.0.beta1_ new myapp_
<2> Die zu diesem Zeitpunkt benötigten RubyGems und deren Abhängigkeiten
    untereinander entnehmen Sie der Datei +Gemfile+.
<3> Konfigurationsdatei mit den Einstellungen für den 
    Datenbankzugriff (Datenbankadapter).        
<4> Wenn Sie nicht berechtigt sind RubyGems zu installieren, müssen Sie 
    die benötigten RubyGems installieren lassen! (Abbruch: [CRTL-C])

----
$ cd MyApp

$ tree -LF 1 .
.
├── app/
├── bin/
├── config/
├── config.ru
├── db/
├── Gemfile
├── lib/
├── log/
├── public/
├── Rakefile
├── README.rdoc
├── test/
├── tmp/
└── vendor/

10 directories, 4 files
----

.Datei: +Gemfile+
----
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0.beta1'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.0.beta1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'   <1>
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'   <2>
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'   <3>

# Use Rails Html Sanitizer for HTML sanitization
gem 'rails-html-sanitizer', '~> 1.0'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'debugger' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exceptions page and /console in development
  gem 'web-console', '~> 2.0.0.beta2'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
----
<1> Der Spezifizierer '~> 4.0.0' ist identisch mit 
    den Bedingungen '>= 4.0.0' und '< 4.1'.  
<2> Der Spezifizierer '~> 2.0' ist identisch mit 
    den Bedingungen '>= 2.0' und '< 3'.    
<3> Der Spezifizierer '~> 3.1.7' ist identisch mit 
    den Bedingungen '>= 3.1.7' und '< 3.2'.    

.Prüfen der Abhängigkeiten im +Gemfile+ (1)
----
$ bundle check
Resolving dependencies...
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.

$ bundle list
Could not find gem 'sdoc (>= 0) ruby' in the gems available on this machine.
----

.Installation der fehlenden Gems mit dem zur Installation berechtigten User _root_!
----
# cd ~sid/RailsDir/MyApp

# bundle check
Resolving dependencies...
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.

# bundle install    <1> <2>
Don't run Bundler as root. Bundler can ask for sudo if it is needed, 
and installing your bundle as root will break
this application for all non-root users on this machine.   
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 10.3.2
Using i18n 0.7.0.beta1
Using json 1.8.1
Using minitest 5.4.2
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0.beta1
Using builder 3.2.2
Using erubis 2.7.0
Using rails-deprecated_sanitizer 1.0.3
Using mini_portile 0.6.0
Using nokogiri 1.6.3.1
Using rails-dom-testing 1.0.3
Using actionview 4.2.0.beta1
Using rack 1.6.0.beta
Using rack-test 0.6.2
Using actionpack 4.2.0.beta1
Using mime-types 2.3
Using mail 2.6.1
Using actionmailer 4.2.0.beta1
Using globalid 0.3.0
Using activejob 4.2.0.beta1
Using activemodel 4.2.0.beta1
Using arel 6.0.0.beta1
Using activerecord 4.2.0.beta1
Installing debug_inspector 0.0.2  
Installing binding_of_caller 0.7.3.pre1
Using bundler 1.7.3
Installing columnize 0.8.9   
Installing debugger-linecache 1.2.0
Installing slop 3.6.0
Installing byebug 3.4.2
Installing coffee-script-source 1.8.0
Installing execjs 2.2.1
Installing coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0.beta1
Installing coffee-rails 4.0.1   
Using hike 1.2.3
Using multi_json 1.10.1
Installing jbuilder 2.1.3   
Installing jquery-rails 3.1.2
Installing loofah 2.0.1
Installing mysql2 0.3.16
Using tilt 1.4.1
Using sprockets 2.12.2
Using sprockets-rails 3.0.0.beta1
Using rails 4.2.0.beta1
Installing rails-html-sanitizer 1.0.1
Using rdoc 4.1.2
Installing sass 3.4.5
Installing sass-rails 5.0.0.beta1
Installing sdoc 0.4.1
Installing spring 1.1.3
Installing turbolinks 2.3.0
Installing uglifier 2.5.3
Installing web-console 2.0.0.beta4
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> Die Ausgabe bezieht sich auf Ruby Version 2.1.3!
<2> Besser mit einem Benutzer der Root-Rechte zeitweise erlangen kann: +
    _bundle install_ und _sudo password_  

.Prüfen der Abhängigkeiten im +Gemfile+ (2)
----
$ bundle check
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 sid  sid  1585 Sep 28 20:34 Gemfile
-rw-r--r-- 1 root root 4210 Sep 28 21:20 Gemfile.lock   <1>
----
<1> Die Rechte an der Datei +Gemfile.lock+ sind durch den Befehl _bundle install_ 
    (als Benutzer 'root') auf den Benutzer 'root' gesetzt!

----
# rm Gemfile.lock
----

----
$ bundle check
Resolving dependencies...
The Gemfile's dependencies are satisfied

$ ls -l Gemfile*
-rw-rw-r-- 1 sid sid 1585 Sep 28 20:34 Gemfile
-rw-rw-r-- 1 sid sid 4210 Sep 28 21:28 Gemfile.lock 
----


Datenbankadapter konfigurieren
------------------------------
.Datei: +config/database.yml+ sqlite3
----
[...]
development:
  adapter: sqlite3
  database: db/development.sqlite3   <1>
  pool: 5
  timeout: 5000
[...]
----
<1> Die Datenbank-Datei wird mit dem ersten Aufruf automatisch angelegt. +
    Keine Angabe für Benutzer und Passwort!

.Datei: +config/database.yml+ mysql 
----
[...]
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: sid                 <---          
  password: GEHEIM              <---
  socket: /var/run/mysqld/mysqld.sock

development:   <1>
  <<: *default
  database: myapp_development   <2>
[...]  
----
<1> Es werden ausschließlich die zu _default_ geänderten Einträge aufgeführt.
<2> Der hier vorgeschlagene Datenbank-Name wird von _Ruby on Rails_
    automatisch aus dem Namen der Applikation und dem Zusatz '_development'
    gebildet.


JavaScript-Runtime installieren
-------------------------------
Für die erzeugte _Ruby on Rails_-Anwendung ist eine JavaScript-Runtime erforderlich.

.Möglichkeit 1: Das RubyGem _therubyracer_

.Datei: +Gemfile+
----
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0.beta1'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.0.beta1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby   <1>
[...]
----
<1> Entfernen Sie das Kommentar-Zeichen '#'.

.bundle install (mit dem Benutzer _root_)
----
# cd ~sid/80/RailsDir/MyApp

# bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rake 10.3.2
Using i18n 0.7.0.beta1
Using json 1.8.1
Using minitest 5.4.2
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0.beta1
Using builder 3.2.2
Using erubis 2.7.0
Using rails-deprecated_sanitizer 1.0.3
Using mini_portile 0.6.0
Using nokogiri 1.6.3.1
Using rails-dom-testing 1.0.3
Using actionview 4.2.0.beta1
Using rack 1.6.0.beta
Using rack-test 0.6.2
Using actionpack 4.2.0.beta1
Using mime-types 2.3
Using mail 2.6.1
Using actionmailer 4.2.0.beta1
Using globalid 0.3.0
Using activejob 4.2.0.beta1
Using activemodel 4.2.0.beta1
Using arel 6.0.0.beta1
Using activerecord 4.2.0.beta1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.3.pre1
Using bundler 1.7.3
Using columnize 0.8.9
Using debugger-linecache 1.2.0
Using slop 3.6.0
Using byebug 3.4.2
Using coffee-script-source 1.8.0
Using execjs 2.2.1
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0.beta1
Using coffee-rails 4.0.1
Using hike 1.2.3
Using multi_json 1.10.1
Using jbuilder 2.1.3
Using jquery-rails 3.1.2
Installing libv8 3.16.14.7   <1>
Using loofah 2.0.1
Using mysql2 0.3.16
Using tilt 1.4.1
Using sprockets 2.12.2
Using sprockets-rails 3.0.0.beta1
Using rails 4.2.0.beta1
Using rails-html-sanitizer 1.0.1
Using rdoc 4.1.2
Installing ref 1.0.5   <1>
Using sass 3.4.5
Using sass-rails 5.0.0.beta1
Using sdoc 0.4.1
Using spring 1.1.3
Installing therubyracer 0.12.1   <1> <2> <3>
Using turbolinks 2.3.0
Using uglifier 2.5.3
Using web-console 2.0.0.beta4
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
<1> Neu installierte RubyGems.
<2> http://rubygems.org/gems/therubyracer[RubyGems.org: therubyracer] +
    Call JavaScript code and manipulate JavaScript objects from Ruby. +
    Call Ruby code and manipulate Ruby objects from JavaScript.
<3> Das RubyGem 'therubyracer' wird kompiliert!

----
# rm Gemfile.lock

$ bundle check
Resolving dependencies...
The Gemfile's dependencies are satisfied
----

.Möglichkeit 2: Das Ubuntu-Paket 'nodejs' installieren
----
$ sudo apt-get -s install nodejs       <1>
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libc-ares2 libv8-3.14.5
Die folgenden NEUEN Pakete werden installiert:
  libc-ares2 libv8-3.14.5 nodejs
0 aktualisiert, 3 neu installiert, 0 zu entfernen und 1 nicht aktualisiert.
Inst libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Inst libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Inst nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
Conf libc-ares2 (1.10.0-2 Ubuntu:14.04/trusty [amd64])
Conf libv8-3.14.5 (3.14.5.8-5ubuntu2 Ubuntu:14.04/trusty [amd64])
Conf nodejs (0.10.25~dfsg2-2ubuntu1 Ubuntu:14.04/trusty [amd64])
----
<1> _apt-get -s ... (simulate)_ ich habe mich dagegen entschieden.


Aufruf der Webanwendung im Browser
----------------------------------
WEBrick wird in _Ruby on Rails_ default-mäßig als Testserver für die 
Entwicklungs-Umgebung verwendet.
----
$ rails s
=> Booting WEBrick
=> Rails 4.2.0.beta1 application starting in development on http://localhost:3000   <1>
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2014-09-28 20:39:54] INFO  WEBrick 1.3.1
[2014-09-28 20:39:54] INFO  ruby 2.1.3 (2014-09-19) [x86_64-linux]   <2>
[2014-09-28 20:39:54] INFO  WEBrick::HTTPServer#start: pid=22778 port=3000
[...]
----
<1> Der Webserver läuft ohne Port-Angabe (_--port_ ...) auf Port 3000.
<2> Ruby Version 2.1.3

----
Browser> http://localhost:3000/   <1>
         About your application’s environment   <2>       
----
<1> Grundsätzlicher Test der Verbindung!
<2> Link zu weiteren Informationen...

----
Browser> http://localhost:3000/rails/info/properties/   <1>
----
<1> Informationen zur ausgeführten Applikation _MyApp_: + 
   (Ruby-Version, RubyGems, Verzeichnis, Umgebung, Datenbank, Datenbank-Schema)

oder

----
$ rake about
[...]
----

.Ausgabe...
----
About your application's environment
Ruby version              2.1.3-p242 (x86_64-linux)   <1>
RubyGems version          2.2.2
Rack version              1.5
Rails version             4.2.0.beta1
JavaScript Runtime        therubyracer (V8)
Active Record version     4.2.0.beta1
Action Pack version       4.2.0.beta1
Action View version       4.2.0.beta1
Action Mailer version     4.2.0.beta1
Active Support version    4.2.0.beta1
Active Model version      4.2.0.beta1
Middleware                Rack::Sendfile, 
                          ActionDispatch::Static, 
                          Rack::Lock, 
                          #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x...>, 
                          Rack::Runtime, 
                          Rack::MethodOverride, 
                          ActionDispatch::RequestId, 
                          Rails::Rack::Logger, 
                          ActionDispatch::ShowExceptions, 
                          ActionDispatch::DebugExceptions, 
                          ActionDispatch::RemoteIp, 
                          ActionDispatch::Reloader, 
                          ActionDispatch::Callbacks, 
                          ActiveRecord::Migration::CheckPending, 
                          ActiveRecord::ConnectionAdapters::ConnectionManagement, 
                          ActiveRecord::QueryCache, 
                          ActionDispatch::Cookies, 
                          ActionDispatch::Session::CookieStore, 
                          ActionDispatch::Flash, 
                          ActionDispatch::ParamsParser, 
                          Rack::Head, 
                          Rack::ConditionalGet, 
                          Rack::ETag
Application root          /home/sid/RailsDir/MyApp
Environment               development
Database adapter          mysql2
Database schema version   0
----
<1> Ruby Version 2.1.3


Anhang
------
Abschließend die Liste der aktuell installierten _RubyGems_.

----
$ gem list --local   <1>

*** LOCAL GEMS ***

actionmailer (4.2.0.beta1)
actionpack (4.2.0.beta1)
actionview (4.2.0.beta1)
activejob (4.2.0.beta1)
activemodel (4.2.0.beta1)
activerecord (4.2.0.beta1)
activesupport (4.2.0.beta1)
arel (6.0.0.beta1)
bigdecimal (1.2.5, 1.2.4)
binding_of_caller (0.7.3.pre1)
builder (3.2.2)
bundler (1.7.3)
byebug (3.4.2)
coffee-rails (4.0.1)
coffee-script (2.3.0)
coffee-script-source (1.8.0)
columnize (0.8.9)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
erubis (2.7.0)
execjs (2.2.1)
globalid (0.3.0)
hike (1.2.3)
i18n (0.7.0.beta1)
io-console (0.4.2)
jbuilder (2.1.3)
jquery-rails (3.1.2)
json (1.8.1)
libv8 (3.16.14.7 x86_64-linux)
loofah (2.0.1)
mail (2.6.1)
mime-types (2.3)
mini_portile (0.6.0)
minitest (5.4.2, 4.7.5)
multi_json (1.10.1)
mysql2 (0.3.16)
nokogiri (1.6.3.1)
power_assert (0.1.4)
psych (2.0.6, 2.0.5)
rack (1.6.0.beta)
rack-test (0.6.2)
rails (4.2.0.beta1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.3)
rails-html-sanitizer (1.0.1)
railties (4.2.0.beta1)
rake (10.3.2, 10.1.0)
rdoc (4.1.2, 4.1.0)
ref (1.0.5)
sass (3.4.5)
sass-rails (5.0.0.beta1)
sdoc (0.4.1)
slop (3.6.0)
spring (1.1.3)
sprockets (2.12.2)
sprockets-rails (3.0.0.beta1)
test-unit (3.0.1, 2.1.3.0)
therubyracer (0.12.1)
thor (0.19.1)
thread_safe (0.3.4)
tilt (1.4.1)
turbolinks (2.3.0)
tzinfo (1.2.2)
uglifier (2.5.3)
web-console (2.0.0.beta4)
----
<1> Anzahl der installierten RubyGems: _62_

